### ISSUE TITLE
compilation of minimal failing because kernel header path not in includes

### ISSUE THREAD

**Issue by andreimatei** [libbpf/libbpf-bootstrap#1]
On Ubuntu 20.10 this happens to me:

```
$ V=1 make minimal
clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I.output -c minimal.bpf.c -o .output/minimal.bpf.o
In file included from minimal.bpf.c:3:
In file included from /usr/include/linux/bpf.h:11:
/usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
```

The rub seems to be that `/usr/include/linux/types.h` wants `asm/types.h` which, on my system, I believe lives in `/usr/include/x86_64-linux-gnu/asm/types.h` (which file just reads `#include <asm-generic/types.h>`), and `/usr/include/x86_64-linux-gnu` does not seem to be among clang's include paths, as demonstrated by the `clang -v` output below.

```
clang -v -g -O2 -target bpf -D__TARGET_ARCH_x86 -I.output -c minimal.bpf.c -o .output/minimal.bpf.o
Ubuntu clang version 11.0.0-2
...
#include "..." search starts here:
#include <...> search starts here:
 .output
 /usr/local/include`
 /usr/lib/llvm-11/lib/clang/11.0.0/include
 /usr/include
End of search list.
```

FWIW, on the gcc side, the preprocessor includes `/usr/include/x86_64-linux-gnu` in the `cpp -v` output.

I'm not sure who's at fault here, or what the correct fix is, but adding `-I/usr/include/x86_64-linux-gnu` makes it work. Changing the source to use `vmlinux.h` instead of `<linux/bpf.h>` also makes it work.

Although I don't believe it to be the case, it is possible that my system got screwed up by me manually installing kernel headers through the Debian package created by the kernel's `deb-pkg` make target. I don't think it's the case because I've verified that `/usr/include/linux/types.h` corresponds to the file provided by the Ubuntu's `linux-libc-dev` package.

**Comment by andreimatei** [comment]
Another observation: clang does seem to want to search that arch-specific dir when not using `-target bpf`:
```
$ clang -v -g -O2  -D__TARGET_ARCH_x86 -I.output -c minimal.bpf.c -o .output/minimal.bpf.o
Ubuntu clang version 11.0.0-2
...
#include "..." search starts here:
#include <...> search starts here:
 .output
 /usr/local/include
 /usr/lib/llvm-11/lib/clang/11.0.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
```

**Comment by anakryiko** [comment]
Oh, I think this is how we deal with it in kernel selftests: https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/Makefile#L215-L224

This seems to be due to using `-target bpf`, so for some systems not all the necessary include paths used... You are right that just using "vmlinux.h" would be enough, but that puts a requirement for kernel BTF on the system, and my goal was to have something to use even without kernel built with BTF...

Do you mind trying the `get_sys_includes` trick and confirming if that works? We can "backport" it here. Not that it's simple and obvious, but should just work.

**Comment by andreimatei** [comment]
It works indeed. Would you like a patch?

**Comment by anakryiko** [comment]
that would be great, thanks. Please also include a comment explaining why we need that.
