### ISSUE TITLE
tools FindBpfObject.cmake may not get correct ARCH for aarch64 and etc.

### ISSUE THREAD

**Issue by woodpenker** [libbpf/libbpf-bootstrap#104]
This line of CMake code(https://github.com/libbpf/libbpf-bootstrap/blob/938651fcef787f3885b7c32792851f8423bf8421/tools/cmake/FindBpfObject.cmake#L144) need to be changed to
 ```
COMMAND sed -e "s/x86_64/x86/" -e "s/aarch64/arm64/" -e "s/ppc64le/powerpc/" -e "s/mips.*/mips/"
```
So that cmake can get correct ARCH (such as arm64for aarch64 platform). Or it will raise an error when building: `GCC error "Must specify a BPF target arch via __TARGET_ARCH_xxx"`(__TARGET_ARCH_aarch64 isn't defined inside `bpf_tracing.h`)

**Comment by anakryiko** [comment]
@woodpenker would you be able to send a PR with this change?

**Comment by anakryiko** [comment]
Fixed by https://github.com/libbpf/libbpf-bootstrap/pull/116
