### ISSUE TITLE
Loading of bpf fails with invalid argument

### ISSUE THREAD

**Issue by pfl** [libbpf/libbpf-bootstrap#12]
Latest (c12658971) libbpf-bootstrap gives errors when loading on Debian testing x86_64 with kernel 5.10.17. Actually, already the compilation step is a bit fishy, as it says:
```
libbpf-bootstrap/src(master)$ make
  MKDIR    .output
  MKDIR    .output/libbpf
  LIB      libbpf.a
  MKDIR    staticobjs
  CC       bpf.o
  CC       btf.o
  CC       libbpf.o
  CC       libbpf_errno.o
  CC       netlink.o
  CC       nlattr.o
  CC       str_error.o
  CC       libbpf_probes.o
  CC       bpf_prog_linfo.o
  CC       xsk.o
  CC       btf_dump.o
  CC       hashmap.o
  CC       ringbuf.o
  AR       libbpf.a
  INSTALL  bpf.h libbpf.h btf.h xsk.h libbpf_util.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h libbpf_common.h
  INSTALL  libbpf.pc
  INSTALL  libbpf.a
  BPF      .output/minimal.bpf.o
  GEN-SKEL .output/minimal.skel.h
libbpf: elf: skipping unrecognized data section(5) .rodata.str1.1
  CC       .output/minimal.o
  BINARY   minimal
  BPF      .output/bootstrap.bpf.o
  GEN-SKEL .output/bootstrap.skel.h
  CC       .output/bootstrap.o
  BINARY   bootstrap
  BPF      .output/uprobe.bpf.o
  GEN-SKEL .output/uprobe.skel.h
libbpf: elf: skipping unrecognized data section(5) .rodata.str1.1
  CC       .output/uprobe.o
  BINARY   uprobe
  BPF      .output/kprobe.bpf.o
  GEN-SKEL .output/kprobe.skel.h
libbpf: elf: skipping unrecognized data section(5) .rodata.str1.1
  CC       .output/kprobe.o
  BINARY   kprobe
  BPF      .output/fentry.bpf.o
  GEN-SKEL .output/fentry.skel.h
libbpf: elf: skipping unrecognized data section(5) .rodata.str1.1
  CC       .output/fentry.o
  BINARY   fentry
```  
In all three cases of GEN-SKEL, the output happens in response to
```
...
llvm-strip -g .output/minimal.bpf.o # strip useless DWARF info
libbpf-bootstrap/tools/bpftool gen skeleton .output/minimal.bpf.o > .output/minimal.skel.h
libbpf: elf: skipping unrecognized data section(5) .rodata.str1.1
...
```
But then running 'minimal' fails with
```
libbpf-bootstrap/src(master)# ./minimal 
libbpf: loading object 'minimal_bpf' from buffer
libbpf: elf: section(2) tp/syscalls/sys_enter_write, size 192, link 0, flags 6, type=1
libbpf: sec 'tp/syscalls/sys_enter_write': found program 'handle_tp' at insn offset 0 (0 bytes), code size 24 insns (192 bytes)
libbpf: elf: section(3) license, size 13, link 0, flags 3, type=1
libbpf: license of minimal_bpf is Dual BSD/GPL
libbpf: elf: section(4) .bss, size 4, link 0, flags 3, type=8
libbpf: elf: section(5) .rodata.str1.1, size 28, link 0, flags 32, type=1
libbpf: elf: skipping unrecognized data section(5) .rodata.str1.1
libbpf: elf: section(6) .BTF, size 494, link 0, flags 0, type=1
libbpf: elf: section(7) .BTF.ext, size 160, link 0, flags 0, type=1
libbpf: elf: section(8) .symtab, size 144, link 13, flags 0, type=2
libbpf: elf: section(9) .reltp/syscalls/sys_enter_write, size 16, link 8, flags 0, type=9
libbpf: looking for externs among 6 symbols...
libbpf: collected 0 externs total
libbpf: map 'minimal_.bss' (global data): at sec_idx 4, offset 0, flags 400.
libbpf: map 0 is "minimal_.bss"
libbpf: sec '.reltp/syscalls/sys_enter_write': collecting relocation for section(2) 'tp/syscalls/sys_enter_write'
libbpf: sec '.reltp/syscalls/sys_enter_write': relo #0: insn #2 against 'my_pid'
libbpf: prog 'handle_tp': found data map 0 (minimal_.bss, sec 4, off 0) for insn 2
libbpf: map 'minimal_.bss': created successfully, fd=4
libbpf: load bpf program failed: Invalid argument
libbpf: failed to load program 'handle_tp'
libbpf: failed to load object 'minimal_bpf'
libbpf: failed to load BPF skeleton 'minimal_bpf': -22
Failed to load and verify BPF skeleton
```
The other programs also fail at the exact same point when loading eBPF programs and with the same error. Might this be an issue with the kernel (v5.10.17, compile by me), clang/llvm (Debian testing versions 11.0.1-2  and 11.0.1), Debian (testing), libbpf-bootstrap (c12658971) or something else?

**Comment by anakryiko** [comment]
Most probably it's your kernel configuration. Check https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/config for the list of Kconfig values that are relevant to BPF functionality. You most probably won't need all of them for libbpf-tools, though. But start with that and see.

**Comment by anakryiko** [comment]
Oh, and `libbpf: elf: skipping unrecognized data section(5) .rodata.str1.1` is just a warning and has no relation to this. This warning will go away once libbpf gets support for merging .rodata sections, for now just ignore it.

**Comment by pfl** [comment]
Yes, it was the kernel configuration due to a reduced set of features. Once enabling
```
CONFIG_KPROBES=y
CONFIG_UPROBES=y
CONFIG_DEBUG_FS=y
CONFIG_FTRACE=y
CONFIG_FTRACE_SYSCALLS=y
CONFIG_KPROBE_EVENTS=y
CONFIG_UPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y
```
with some of those and others getting enabled along the way, the eBPF code started working.

Thanks for the kernel configuration pointer!

**Comment by yenk86** [comment]
@pfl Hello 
Please I am starting with eBPF but I have the same issue you described up there.
I have tried you solution by changing the configurations inside the .config file, but the error stays.
I have cloned the project here : https://github.com/libbpf/libbpf-bootstrap

**Comment by yenk86** [comment]
That's the issue;
utrqins@utrqins-Latitude-E7470:~/Documents/test/libbpf-bootstrap/examples/c$ make
  MKDIR    .output
  MKDIR    .output/libbpf
  LIB      libbpf.a
  MKDIR    /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/bpf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/btf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/libbpf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/libbpf_errno.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/netlink.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/nlattr.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/str_error.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/libbpf_probes.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/bpf_prog_linfo.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/btf_dump.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/hashmap.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/ringbuf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/strset.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/linker.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/gen_loader.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/relo_core.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/usdt.o
  AR       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/libbpf.a
  INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h usdt.bpf.h
  INSTALL  /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/libbpf.pc
  INSTALL  /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/libbpf.a 
  BPF      .output/usdt.bpf.o
  MKDIR    bpftool
  BPFTOOL  bpftool/bootstrap/bpftool
...                        libbfd: [ OFF ]
...        disassembler-four-args: [ OFF ]
...                          zlib: [ on  ]
...                        libcap: [ OFF ]
...               clang-bpf-co-re: [ OFF ]
  MKDIR    /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/include/bpf
  INSTALL  /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/include/bpf/hashmap.h
  INSTALL  /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/include/bpf/relo_core.h
  INSTALL  /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/include/bpf/libbpf_internal.h
  MKDIR    /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/
  MKDIR    /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/
  MKDIR    /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/bpf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/btf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/libbpf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/libbpf_errno.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/netlink.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/nlattr.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/str_error.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/libbpf_probes.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/bpf_prog_linfo.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/btf_dump.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/hashmap.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/ringbuf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/strset.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/linker.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/gen_loader.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/relo_core.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/usdt.o
  AR       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/libbpf.a
  INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h usdt.bpf.h
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/main.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/common.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/json_writer.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/gen.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/btf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/xlated_dumper.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/btf_dumper.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/disasm.o
  LINK     /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/bpftool
  GEN-SKEL .output/usdt.skel.h
libbpf: sec '.relusdt/libc.so.6:libc:setjmp': corrupted symbol #29 pointing to invalid section #65522 for relo #3
Error: failed to open BPF object file: BPF object format invalid
make: *** [Makefile:112: .output/usdt.skel.h] Error 95
make: *** Deleting file '.output/usdt.skel.h'

**Comment by anakryiko** [comment]
What's your Clang version? Try getting newer one.
