### ISSUE TITLE
LSM program failed to attach

### ISSUE THREAD

**Issue by JackyYin** [libbpf/libbpf-bootstrap#122]
Greeting,
I'm trying to run a simple LSM ebpf program, but failed to attach it to kernel.

I encountered the same issue in `fentry` example too, is it related to the macro `BPF_PROG` ?

my kernel version: `5.15.73`
my CPU architecture: `aarch64`

ebpf program:
```c
SEC("lsm/socket_create")
int BPF_PROG(socket_create_handler, int family, int type, int protocol, int kern, int ret)
{
    if(ret)
        return ret;

    bpf_printk("family: %d, type: %d, protocol: %d\n", family, type, protocol);
    return 0;
}
```

error message:
```
...
libbpf: prog 'socket_create_handler': failed to attach: ERROR: streeror_r(-524)=22
libbpf: prog 'socket_create_handler': failed to auto-attach: -524
```

**Comment by anakryiko** [comment]
This might be an ARM64 limitation, but I don't have much experience with ARM64, unfortunately. Please ask on the mailing list, see https://github.com/libbpf/libbpf#libbpf-and-general-bpf-usage-questions.

**Comment by anakryiko** [comment]
BTW, confirmed, ARM64 currently doesn't support BPF trampoline, which means fentry/fexit/fmod_ret and lsm programs don't work on ARM64.
