### ISSUE TITLE
make examples/c/ failed 

### ISSUE THREAD

**Issue by Wu-Fisher** [libbpf/libbpf-bootstrap#128]
When I make here, I got these below:
```
GEN-SKEL .output/usdt.skel.h
libbpf: sec '.relusdt/libc.so.6:libc:setjmp': corrupted symbol #29 pointing to invalid section #65522 for relo #3
Error: failed to open BPF object file: BPF object format invalid
make: *** [Makefile:112: .output/usdt.skel.h] Error 95
make: *** Deleting file '.output/usdt.skel.h'
```
But when I make + (for example bootstrap), it works well(make: 'bootstrap' is up to date.)

**Comment by anakryiko** [comment]
Sorry, it's not clear. What's "make here"? Can you elaborate?

**Comment by doujianli** [comment]
Maybe you should update clang. I fixed the problem with clang-15.

**Comment by ruoxianglee** [comment]
I have the same problem with clang-10. It can be fixed by updating to clang-11.

**Comment by Wu-Fisher** [comment]
woh， thank u all. I got it too.
