### ISSUE TITLE
excute usdt failed,why?

### ISSUE THREAD

**Issue by LinuxVWQH** [libbpf/libbpf-bootstrap#132]
root@b30121bce996:/# usdt
libbpf: loading object 'usdt_bpf' from buffer
libbpf: elf: section(2) .text, size 1552, link 0, flags 6, type=1
libbpf: sec '.text': found program 'bpf_usdt_arg_cnt' at insn offset 0 (0 bytes), code size 36 insns (288 bytes)
libbpf: sec '.text': found program 'bpf_usdt_arg' at insn offset 36 (288 bytes), code size 126 insns (1008 bytes)
libbpf: sec '.text': found program 'bpf_usdt_cookie' at insn offset 162 (1296 bytes), code size 32 insns (256 bytes)
libbpf: elf: section(3) .rel.text, size 144, link 17, flags 40, type=9
libbpf: elf: section(4) usdt/libc.so.6:libc:setjmp, size 264, link 0, flags 6, type=1
libbpf: sec 'usdt/libc.so.6:libc:setjmp': found program 'usdt_auto_attach' at insn offset 0 (0 bytes), code size 33 insns (264 bytes)
libbpf: elf: section(5) .relusdt/libc.so.6:libc:setjmp, size 80, link 17, flags 40, type=9
libbpf: elf: section(6) usdt, size 208, link 0, flags 6, type=1
libbpf: sec 'usdt': found program 'usdt_manual_attach' at insn offset 0 (0 bytes), code size 26 insns (208 bytes)
libbpf: elf: section(7) .relusdt, size 64, link 17, flags 40, type=9
libbpf: elf: section(8) .maps, size 64, link 0, flags 3, type=1
libbpf: elf: section(9) license, size 13, link 0, flags 3, type=1
libbpf: license of usdt_bpf is Dual BSD/GPL
libbpf: elf: section(10) .bss, size 4, link 0, flags 3, type=8
libbpf: elf: section(11) .rodata, size 136, link 0, flags 2, type=1
libbpf: elf: section(12) .BTF, size 3675, link 0, flags 0, type=1
libbpf: elf: section(14) .BTF.ext, size 1804, link 0, flags 0, type=1
libbpf: elf: section(17) .symtab, size 744, link 1, flags 0, type=2
libbpf: looking for externs among 31 symbols...
libbpf: collected 1 externs total
libbpf: extern (kcfg) #0: symbol 22, off 0, name LINUX_HAS_BPF_COOKIE
libbpf: map '__bpf_usdt_specs': at sec_idx 8, offset 0.
libbpf: map '__bpf_usdt_specs': found type = 2.
libbpf: map '__bpf_usdt_specs': found key [2], sz = 4.
libbpf: map '__bpf_usdt_specs': found value [9], sz = 208.
libbpf: map '__bpf_usdt_specs': found max_entries = 256.
libbpf: map '__bpf_usdt_ip_to_spec_id': at sec_idx 8, offset 32.
libbpf: map '__bpf_usdt_ip_to_spec_id': found type = 1.
libbpf: map '__bpf_usdt_ip_to_spec_id': found key [26], sz = 8.
libbpf: map '__bpf_usdt_ip_to_spec_id': found value [28], sz = 4.
libbpf: map '__bpf_usdt_ip_to_spec_id': found max_entries = 1024.
libbpf: map 'usdt_bpf.bss' (global data): at sec_idx 10, offset 0, flags 400.
libbpf: map 2 is "usdt_bpf.bss"
libbpf: map 'usdt_bpf.rodata' (global data): at sec_idx 11, offset 0, flags 480.
libbpf: map 3 is "usdt_bpf.rodata"
libbpf: map 'usdt_bp.kconfig' (global data): at sec_idx 17, offset 0, flags 480.
libbpf: map 4 is "usdt_bp.kconfig"
libbpf: sec '.rel.text': collecting relocation for section(2) '.text'
libbpf: sec '.rel.text': relo #0: insn #0 against 'LINUX_HAS_BPF_COOKIE'
libbpf: prog 'bpf_usdt_arg_cnt': found extern #0 'LINUX_HAS_BPF_COOKIE' (sym 22) for insn #0
libbpf: sec '.rel.text': relo #1: insn #8 against '__bpf_usdt_ip_to_spec_id'
libbpf: prog 'bpf_usdt_arg_cnt': found map 1 (__bpf_usdt_ip_to_spec_id, sec 8, off 32) for insn #8
libbpf: sec '.rel.text': relo #2: insn #27 against '__bpf_usdt_specs'
libbpf: prog 'bpf_usdt_arg_cnt': found map 0 (__bpf_usdt_specs, sec 8, off 0) for insn #27
libbpf: sec '.rel.text': relo #3: insn #41 against 'LINUX_HAS_BPF_COOKIE'
libbpf: prog 'bpf_usdt_arg': found extern #0 'LINUX_HAS_BPF_COOKIE' (sym 22) for insn #5
libbpf: sec '.rel.text': relo #4: insn #49 against '__bpf_usdt_ip_to_spec_id'
libbpf: prog 'bpf_usdt_arg': found map 1 (__bpf_usdt_ip_to_spec_id, sec 8, off 32) for insn #13
libbpf: sec '.rel.text': relo #5: insn #69 against '__bpf_usdt_specs'
libbpf: prog 'bpf_usdt_arg': found map 0 (__bpf_usdt_specs, sec 8, off 0) for insn #33
libbpf: sec '.rel.text': relo #6: insn #162 against 'LINUX_HAS_BPF_COOKIE'
libbpf: prog 'bpf_usdt_cookie': found extern #0 'LINUX_HAS_BPF_COOKIE' (sym 22) for insn #0
libbpf: sec '.rel.text': relo #7: insn #170 against '__bpf_usdt_ip_to_spec_id'
libbpf: prog 'bpf_usdt_cookie': found map 1 (__bpf_usdt_ip_to_spec_id, sec 8, off 32) for insn #8
libbpf: sec '.rel.text': relo #8: insn #187 against '__bpf_usdt_specs'
libbpf: prog 'bpf_usdt_cookie': found map 0 (__bpf_usdt_specs, sec 8, off 0) for insn #25
libbpf: sec '.relusdt/libc.so.6:libc:setjmp': collecting relocation for section(4) 'usdt/libc.so.6:libc:setjmp'
libbpf: sec '.relusdt/libc.so.6:libc:setjmp': relo #0: insn #4 against 'bpf_usdt_arg'
libbpf: sec '.relusdt/libc.so.6:libc:setjmp': relo #1: insn #10 against 'bpf_usdt_arg'
libbpf: sec '.relusdt/libc.so.6:libc:setjmp': relo #2: insn #16 against 'bpf_usdt_arg'
libbpf: sec '.relusdt/libc.so.6:libc:setjmp': relo #3: insn #20 against 'my_pid'
libbpf: prog 'usdt_auto_attach': found data map 2 (usdt_bpf.bss, sec 10, off 0) for insn 20
libbpf: sec '.relusdt/libc.so.6:libc:setjmp': relo #4: insn #24 against '.rodata'
libbpf: prog 'usdt_auto_attach': found data map 3 (usdt_bpf.rodata, sec 11, off 0) for insn 24
libbpf: sec '.relusdt': collecting relocation for section(6) 'usdt'
libbpf: sec '.relusdt': relo #0: insn #4 against 'bpf_usdt_arg'
libbpf: sec '.relusdt': relo #1: insn #10 against 'bpf_usdt_arg'
libbpf: sec '.relusdt': relo #2: insn #16 against 'bpf_usdt_arg'
libbpf: sec '.relusdt': relo #3: insn #18 against '.rodata'
libbpf: prog 'usdt_manual_attach': found data map 3 (usdt_bpf.rodata, sec 11, off 0) for insn 18
libbpf: loading kernel BTF '/sys/kernel/btf/vmlinux': 0
libbpf: extern (kcfg) 'LINUX_HAS_BPF_COOKIE': set to 0x1
libbpf: map '__bpf_usdt_specs': created successfully, fd=4
libbpf: map '__bpf_usdt_ip_to_spec_id': created successfully, fd=5
libbpf: map 'usdt_bpf.bss': created successfully, fd=6
libbpf: map 'usdt_bpf.rodata': created successfully, fd=7
libbpf: map 'usdt_bp.kconfig': created successfully, fd=8
libbpf: sec '.text': found 3 CO-RE relocations
libbpf: CO-RE relocating [33] struct pt_regs: found target candidate [224] struct pt_regs in [vmlinux]
libbpf: prog 'bpf_usdt_arg_cnt': relo #0: <byte_off> [33] struct pt_regs.ip (0:16 @ offset 128)
libbpf: prog 'bpf_usdt_arg_cnt': relo #0: matching candidate #0 <byte_off> [224] struct pt_regs.ip (0:16 @ offset 128)
libbpf: prog 'bpf_usdt_arg_cnt': relo #0: patched insn #4 (LDX/ST/STX) off 128 -> 128
libbpf: prog 'bpf_usdt_arg': relo #1: <byte_off> [33] struct pt_regs.ip (0:16 @ offset 128)
libbpf: prog 'bpf_usdt_arg': relo #1: matching candidate #0 <byte_off> [224] struct pt_regs.ip (0:16 @ offset 128)
libbpf: prog 'bpf_usdt_arg': relo #1: patched insn #9 (LDX/ST/STX) off 128 -> 128
libbpf: prog 'bpf_usdt_cookie': relo #2: <byte_off> [33] struct pt_regs.ip (0:16 @ offset 128)
libbpf: prog 'bpf_usdt_cookie': relo #2: matching candidate #0 <byte_off> [224] struct pt_regs.ip (0:16 @ offset 128)
libbpf: prog 'bpf_usdt_cookie': relo #2: patched insn #4 (LDX/ST/STX) off 128 -> 128
libbpf: prog 'usdt_auto_attach': added 126 insns from sub-prog 'bpf_usdt_arg'
libbpf: prog 'usdt_auto_attach': insn #4 relocated, imm 28 points to subprog 'bpf_usdt_arg' (now at 33 offset)
libbpf: prog 'usdt_auto_attach': insn #10 relocated, imm 22 points to subprog 'bpf_usdt_arg' (now at 33 offset)
libbpf: prog 'usdt_auto_attach': insn #16 relocated, imm 16 points to subprog 'bpf_usdt_arg' (now at 33 offset)
libbpf: prog 'usdt_manual_attach': added 126 insns from sub-prog 'bpf_usdt_arg'
libbpf: prog 'usdt_manual_attach': insn #4 relocated, imm 21 points to subprog 'bpf_usdt_arg' (now at 26 offset)
libbpf: prog 'usdt_manual_attach': insn #10 relocated, imm 15 points to subprog 'bpf_usdt_arg' (now at 26 offset)
libbpf: prog 'usdt_manual_attach': insn #16 relocated, imm 9 points to subprog 'bpf_usdt_arg' (now at 26 offset)
libbpf: prog 'usdt_manual_attach': failed to resolve full path for 'libc.so.6': -2
Failed to attach BPF program `usdt_manual_attach`
root@b30121bce996:/# ldd /home/james/workspace/libbpf-bootstrap/examples/c/usdt
        linux-vdso.so.1 (0x00007fff31daa000)
        libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x00007f6f1e2a4000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6f1e288000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6f1e060000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6f1e319000)
root@b30121bce996:/# ls /lib/x86_64-linux-gnu/libc.so.6
/lib/x86_64-linux-gnu/libc.so.6

**Comment by anakryiko** [comment]
I wonder if you are running into issue fixed by https://github.com/libbpf/libbpf/commit/9da0dcb62149ab0a6c5711813d77a844ec6f393b ? I've updated libbpf submodule to get that fix. Can you please try again with latest libbpf-bootstrap and libbpf version?

**Comment by LinuxVWQH** [comment]
@anakryiko thanks,it is useful:)

**Comment by anakryiko** [comment]
> @anakryiko thanks,it is useful:)

but did it help? Please check and close the issue, if it did. Thank you!
