### ISSUE TITLE
failed to create map for 'minimal_.rodata' when run minimal in kernel v5.4

### ISSUE THREAD

**Issue by zhouchuyi** [libbpf/libbpf-bootstrap#135]
Hi,
minimal seems can not run in kernel v5.4 when create map for rodata.

> libbpf: loading object 'minimal_bpf' from buffer
libbpf: elf: section(3) tp/syscalls/sys_enter_write, size 104, link 0, flags 6, type=1
libbpf: sec 'tp/syscalls/sys_enter_write': found program 'handle_tp' at insn offset 0 (0 bytes), code size 13 insns (104 bytes)
libbpf: elf: section(4) .reltp/syscalls/sys_enter_write, size 32, link 13, flags 40, type=9
libbpf: elf: section(5) license, size 13, link 0, flags 3, type=1
libbpf: license of minimal_bpf is Dual BSD/GPL
libbpf: elf: section(6) .bss, size 4, link 0, flags 3, type=8
libbpf: elf: section(7) .rodata, size 28, link 0, flags 2, type=1
libbpf: elf: section(8) .BTF, size 601, link 0, flags 0, type=1
libbpf: elf: section(10) .BTF.ext, size 160, link 0, flags 0, type=1
libbpf: elf: section(13) .symtab, size 192, link 1, flags 0, type=2
libbpf: looking for externs among 8 symbols...
libbpf: collected 0 externs total
libbpf: map 'minimal_.bss' (global data): at sec_idx 6, offset 0, flags 400.
libbpf: map 0 is "minimal_.bss"
libbpf: map 'minimal_.rodata' (global data): at sec_idx 7, offset 0, flags 80.
libbpf: map 1 is "minimal_.rodata"
libbpf: sec '.reltp/syscalls/sys_enter_write': collecting relocation for section(3) 'tp/syscalls/sys_enter_write'
libbpf: sec '.reltp/syscalls/sys_enter_write': relo #0: insn #2 against 'my_pid'
libbpf: prog 'handle_tp': found data map 0 (minimal_.bss, sec 6, off 0) for insn 2
libbpf: sec '.reltp/syscalls/sys_enter_write': relo #1: insn #6 against '.rodata'
libbpf: prog 'handle_tp': found data map 1 (minimal_.rodata, sec 7, off 0) for insn 6
libbpf: map 'minimal_.bss': created successfully, fd=4
libbpf: Error in bpf_create_map_xattr(minimal_.rodata):Invalid argument(-22). Retrying without BTF.
libbpf: map 'minimal_.rodata': failed to create: Invalid argument(-22)
libbpf: failed to load object 'minimal_bpf'
libbpf: failed to load BPF skeleton 'minimal_bpf': -22

However, it works fine in kernel v5.10.  Both of them has enabled required BTF & BPF configs when compiling them.
So I was wondering what cause this problem, since in our production environment it is almost always version 5.4.
Thanks

**Comment by anakryiko** [comment]
Not sure, tbh. Required features seems to require v5.2, so v5.4 should be working fine. Try running minimal_legacy and see if that works. Otherwise we'd need to debug this using tools like https://github.com/anakryiko/retsnoop, it's hard to know from just -EINVAL (-22) error code.

**Comment by zhouchuyi** [comment]
Thanks for your reply!

Almost all the demo could run... minimal_legacy also shows 
`map '.rodata.str1.1': failed to create: Invalid argument(-22)`
It seems kernel could not handle BPF_MAP_CREATE for dodata properly....

**Comment by zhouchuyi** [comment]
> Not sure, tbh. Required features seems to require v5.2, so v5.4 should be working fine. Try running minimal_legacy and see if that works. Otherwise we'd need to debug this using tools like https://github.com/anakryiko/retsnoop, it's hard to know from just -EINVAL (-22) error code.

Thanks for your reply!

Almost all the demo could run... minimal_legacy also shows
map '.rodata.str1.1': failed to create: Invalid argument(-22)
It seems kernel could not handle BPF_MAP_CREATE for dodata properly....

**Comment by anakryiko** [comment]
@zhouchuyi were you able to understand why kernel rejects BPF_MAP_CREATE command? 

As a work around, you can add `#define BPF_NO_GLOBAL_DATA` before `#include <bpf/bpf_helpers.h>` to make bpf_printk() not use static variables. That will eliminate the need to have .rodata.str1.1.

But it would be nice if you can help investigate why this failure happens in the first place.
