### ISSUE TITLE
libbpf: Error in bpf_object__probe_loading():Function not implemented(38). Couldn't load trivial BPF program. Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value.

### ISSUE THREAD

**Issue by LinuxVWQH** [libbpf/libbpf-bootstrap#139]
Hello！
     when i excute bootstrap in my system,i got a strange problem:

![image](https://user-images.githubusercontent.com/74600097/209068276-7ba4b0bf-c819-4cc5-9181-867a5c657b26.png)
![image](https://user-images.githubusercontent.com/74600097/209068524-d2b172f0-9ae5-4bd6-ab8a-a9badbeb2303.png)
but the CONFIG_BPF_SYSCALL is ok in my kernel menuconfig,i try to modify:/etc/security/limits.conf,but it is unuseful.
https://github.com/RPCS3/rpcs3/issues/9328
who can help me?
ps 1：
`root@e04-g4:/# uname -a
Linux e04-g4 5.10.110-yocto-standard #1 SMP PREEMPT Tue Dec 13 11:18:44 UTC 2022 aarch64 GNU/Linux
`
ps 2:
![image](https://user-images.githubusercontent.com/74600097/209068652-d87a8da5-bda0-4f53-b63e-ba8479a182f4.png)

**Comment by anakryiko** [comment]
For bootstrap, see relo #2 failure. It means that you don't have sched_process_exec tracepoints enabled/available in your kernel. So it's definitely some sort of kernel configuration issue. You might want to see which of config values in https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/config  you'd need to make everything work. You won't need all of them (all of them are needed only for running all of BPF selftests), but there are important ones that you most probaly need to do useful BPF work.

**Comment by LinuxVWQH** [comment]
@anakryiko you are right,thank you:)!It is the CONFIG_BPF_SYSCALL is not takeing effect,I set the CONFIG_BPF_SYSCALL equal to  y,The bootstrap can work!
