### ISSUE TITLE
Where do we get vmlinux.h?

### ISSUE THREAD

**Issue by k82cn** [libbpf/libbpf-bootstrap#14]
Hi team,

I'm learning ebpf, and would like to build an app from scratch. So I'd like to know where to get `vmlinux.h`?

BTW, do we have slack?

-- K

**Comment by anakryiko** [comment]
see https://github.com/libbpf/libbpf-bootstrap/blob/master/tools/gen_vmlinux_h.sh

I personally am not on any Slack. bpf@vger.kernel.org is where all the BPF development is happening and users sometimes ask their questions there. There is also iovisor-dev mailing list, which is pretty active. ebpf.io also has its own Slack, you can try that: https://ebpf.io/slack

**Comment by k82cn** [comment]
thanks very much! I'm going to move my question to those channel :)
