### ISSUE TITLE
excute kprobe failed on ARM-64

### ISSUE THREAD

**Issue by LinuxVWQH** [libbpf/libbpf-bootstrap#140]
Hi，when i installed the kprobe tools in my OS,I get a problem:
![image](https://user-images.githubusercontent.com/74600097/210333640-06dd5af0-beba-47f0-b07b-6965cc6279f5.png)
![image](https://user-images.githubusercontent.com/74600097/210333697-c11736d8-ebb8-4f24-bed2-27077d59a7d1.png)
I try to take some measures but not useful,please help me,thanks!
**PS1**:
OS_info:
`Linux e04-g4 5.10.110-yocto-standard #1 SMP PREEMPT Tue Jan 3 09:00:28 UTC 2023 aarch64 GNU/Linux`
**PS2**:
KERNEL_CONFIG
`CONFIG_TASKS_TRACE_RCU=y
CONFIG_BPF_SYSCALL=y
CONFIG_TRACEPOINTS=y
CONFIG_UPROBES=y
CONFIG_BINARY_PRINTF=y

CONFIG_DEBUG_INFO_BTF=y
CONFIG_STACKTRACE=y
CONFIG_NOP_TRACER=y
CONFIG_RING_BUFFER=y
CONFIG_EVENT_TRACING=y
CONFIG_CONTEXT_SWITCH_TRACER=y
CONFIG_TRACING=y
CONFIG_FTRACE=y
CONFIG_FTRACE_SYSCALLS=y
CONFIG_BRANCH_PROFILE_NONE=y
CONFIG_UPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y
CONFIG_DYNAMIC_EVENTS=y
CONFIG_PROBE_EVENTS=y
CONFIG_CGROUP_BPF=y
CONFIG_SOCK_CGROUP_DATA=y
CONFIG_BPF_LSM=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_USERMODE_DRIVER=y
CONFIG_KPROBES=y
CONFIG_KRETPROBES=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_STREAM_PARSER=y
CONFIG_NET_SOCK_MSG=y
CONFIG_KPROBE_EVENTS=y
CONFIG_FUNCTION_ERROR_INJECTION=y
CONFIG_DEBUG_FS=y
CONFIG_KPROBES_ON_FTRACE=y
CONFIG_HAVE_KPROBES_ON_FTRACE=y
CONFIG_HAVE_DYNAMIC_FTRACE_WITH_ARGS=y
CONFIG_DYNAMIC_FTRACE_WITH_DIRECT_CALLS=y
CONFIG_FTRACE_MCOUNT_USE_CC=y
CONFIG_SECURITY=y
CONFIG_SECURITY_NETWORK=y

#third
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_LWTUNNEL=y
CONFIG_LWTUNNEL_BPF=y

#fourth
CONFIG_IKHEADERS=y
CONFIG_HAVE_BPF_JIT=y
CONFIG_BPF_JIT=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_DEBUG_INFO=y

CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_BPF_KPROBE_OVERRIDE=y
`

**Comment by ThinkerYzu1** [comment]
How did you install kprobe tools?  You said you executed it on an ARM-64 platform, right?  However, according to your log, the kprobe expects an x86 platform.  It asked for `pt_regs.ax` & `pt_regs.si`.  They are apparent x86 register names.

**Comment by ThinkerYzu1** [comment]
Since you did cross-compilation, we may need to make a change against the makefile.  IIRC, the makefile now uses the ARCH of the building machine. Edit `examples/c/Makefile`.  Overwrite the line of `ARCH := ....` to get the correct string.  In your case, you should put `arm64` there.  I hope it fixes your problem!

**Comment by ThinkerYzu1** [comment]
Please try PR #142 .  It may fix your issue by passing `ARCH=arm64` to `make`.  For example, `make ARCH=arm64 .....`.

**Comment by LinuxVWQH** [comment]
> 

hhh,I found the issue after you notice me that structs exisit problem,I had processed that problem and  prepared commit a bug fix,I had no ideal you had fixed it!:)

**Comment by LinuxVWQH** [comment]
Done

**Comment by LinuxVWQH** [comment]
> Hi，when i installed the kprobe tools in my OS,I get a problem: ![image](https://user-images.githubusercontent.com/74600097/210333640-06dd5af0-beba-47f0-b07b-6965cc6279f5.png) ![image](https://user-images.githubusercontent.com/74600097/210333697-c11736d8-ebb8-4f24-bed2-27077d59a7d1.png) I try to take some measures but not useful,please help me,thanks! **PS1**: OS_info: `Linux e04-g4 5.10.110-yocto-standard #1 SMP PREEMPT Tue Jan 3 09:00:28 UTC 2023 aarch64 GNU/Linux` **PS2**: KERNEL_CONFIG `CONFIG_TASKS_TRACE_RCU=y CONFIG_BPF_SYSCALL=y CONFIG_TRACEPOINTS=y CONFIG_UPROBES=y CONFIG_BINARY_PRINTF=y
> 
> CONFIG_DEBUG_INFO_BTF=y CONFIG_STACKTRACE=y CONFIG_NOP_TRACER=y CONFIG_RING_BUFFER=y CONFIG_EVENT_TRACING=y CONFIG_CONTEXT_SWITCH_TRACER=y CONFIG_TRACING=y CONFIG_FTRACE=y CONFIG_FTRACE_SYSCALLS=y CONFIG_BRANCH_PROFILE_NONE=y CONFIG_UPROBE_EVENTS=y CONFIG_BPF_EVENTS=y CONFIG_DYNAMIC_EVENTS=y CONFIG_PROBE_EVENTS=y CONFIG_CGROUP_BPF=y CONFIG_SOCK_CGROUP_DATA=y CONFIG_BPF_LSM=y CONFIG_BPF_JIT_ALWAYS_ON=y CONFIG_USERMODE_DRIVER=y CONFIG_KPROBES=y CONFIG_KRETPROBES=y CONFIG_BPF_STREAM_PARSER=y CONFIG_STREAM_PARSER=y CONFIG_NET_SOCK_MSG=y CONFIG_KPROBE_EVENTS=y CONFIG_FUNCTION_ERROR_INJECTION=y CONFIG_DEBUG_FS=y CONFIG_KPROBES_ON_FTRACE=y CONFIG_HAVE_KPROBES_ON_FTRACE=y CONFIG_HAVE_DYNAMIC_FTRACE_WITH_ARGS=y CONFIG_DYNAMIC_FTRACE_WITH_DIRECT_CALLS=y CONFIG_FTRACE_MCOUNT_USE_CC=y CONFIG_SECURITY=y CONFIG_SECURITY_NETWORK=y
> 
> #third CONFIG_NET_CLS_BPF=m CONFIG_NET_ACT_BPF=m CONFIG_LWTUNNEL=y CONFIG_LWTUNNEL_BPF=y
> 
> #fourth CONFIG_IKHEADERS=y CONFIG_HAVE_BPF_JIT=y CONFIG_BPF_JIT=y CONFIG_HAVE_EBPF_JIT=y CONFIG_DEBUG_INFO=y
> 
> CONFIG_NETFILTER_XT_MATCH_BPF=m CONFIG_BPF_KPROBE_OVERRIDE=y `
