### ISSUE TITLE
Error: failed to open BPF object file: BPF object format invalid

### ISSUE THREAD

**Issue by yenk86** [libbpf/libbpf-bootstrap#147]
Good morning, I am starting learning to code with eBPF but I have many issues when compiling the files.
I clone the project here : https://github.com/libbpf/libbpf-bootstrap, cloning submodules.
After that I have tried to compile the files located in the examples/c folder, but I have the fllowing error : 

utrqins@utrqins-Latitude-E7470:~/Documents/test/libbpf-bootstrap/examples/c$ make
  MKDIR    .output
  MKDIR    .output/libbpf
  LIB      libbpf.a
  MKDIR    /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/bpf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/btf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/libbpf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/libbpf_errno.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/netlink.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/nlattr.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/str_error.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/libbpf_probes.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/bpf_prog_linfo.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/btf_dump.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/hashmap.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/ringbuf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/strset.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/linker.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/gen_loader.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/relo_core.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/usdt.o
  AR       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/libbpf.a
  INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h usdt.bpf.h
  INSTALL  /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/libbpf.pc
  INSTALL  /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output//libbpf/libbpf.a 
  BPF      .output/usdt.bpf.o
  MKDIR    bpftool
  BPFTOOL  bpftool/bootstrap/bpftool
...                        libbfd: [ OFF ]
...        disassembler-four-args: [ OFF ]
...                          zlib: [ on  ]
...                        libcap: [ OFF ]
...               clang-bpf-co-re: [ OFF ]
  MKDIR    /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/include/bpf
  INSTALL  /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/include/bpf/hashmap.h
  INSTALL  /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/include/bpf/relo_core.h
  INSTALL  /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/include/bpf/libbpf_internal.h
  MKDIR    /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/
  MKDIR    /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/
  MKDIR    /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/bpf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/btf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/libbpf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/libbpf_errno.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/netlink.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/nlattr.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/str_error.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/libbpf_probes.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/bpf_prog_linfo.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/btf_dump.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/hashmap.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/ringbuf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/strset.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/linker.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/gen_loader.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/relo_core.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/staticobjs/usdt.o
  AR       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/libbpf.a
  INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h usdt.bpf.h
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/main.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/common.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/json_writer.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/gen.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/btf.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/xlated_dumper.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/btf_dumper.o
  CC       /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/disasm.o
  LINK     /home/utrqins/Documents/test/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/bpftool
  GEN-SKEL .output/usdt.skel.h
libbpf: sec '.relusdt/libc.so.6:libc:setjmp': corrupted symbol #29 pointing to invalid section #65522 for relo #3
Error: failed to open BPF object file: BPF object format invalid
make: *** [Makefile:112: .output/usdt.skel.h] Error 95
make: *** Deleting file '.output/usdt.skel.h'

**Comment by anakryiko** [comment]
It seems like your Clang compiler is too old. Try upgrading it to at least version 12+, and if that doesn't help, please report back.

**Comment by yaunsky** [comment]
Clang has been upgraded to version 12, but the same error still persists.
<img width="939" alt="image" src="https://user-images.githubusercontent.com/48243087/225194093-fb3ebba1-96a6-48c2-92e4-2c5ae6b92d2a.png">

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/48243087/225194152-80d707a9-7dc5-40de-924c-884a2cf92e77.png">
