### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by mingjie-gmj** [libbpf/libbpf-bootstrap#15]
[root@x src]# yum install clang

[root@x src]# make
  MKDIR    .output
  MKDIR    .output/libbpf
  LIB      libbpf.a
  MKDIR    staticobjs
  CC       bpf.o
  CC       btf.o
  CC       libbpf.o
  CC       libbpf_errno.o
  CC       netlink.o
  CC       nlattr.o
  CC       str_error.o
  CC       libbpf_probes.o
  CC       bpf_prog_linfo.o
  CC       xsk.o
  CC       btf_dump.o
  CC       hashmap.o
  CC       ringbuf.o
  AR       libbpf.a
  INSTALL  bpf.h libbpf.h btf.h xsk.h libbpf_util.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h libbpf_common.h
  INSTALL  libbpf.pc
  INSTALL  libbpf.a
  BPF      .output/minimal.bpf.o
error: unknown target triple 'bpf', please use -triple or -arch
make: *** [.output/minimal.bpf.o]

**Comment by mingjie-gmj** [comment]
centos7.8

**Comment by anakryiko** [comment]
You need Clang10+ with support for -target bpf. Check both, please.

**Comment by mingjie-gmj** [comment]
thanks I will upgrade clang
