### ISSUE TITLE
Hello, the argp tutorial link mentioned in your blog does not exist. Can I obtain this tutorial from here?

### ISSUE THREAD

**Issue by yaunsky** [libbpf/libbpf-bootstrap#162]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/48243087/227148413-7fb92001-c636-4d7e-8e63-4bf0a6a6c071.png">

Hello, the argp tutorial link mentioned in your blog does not exist. Can I obtain this tutorial from here?

**Comment by anakryiko** [comment]
Thanks for the report! I updated the link to a new location at http://nongnu.askapache.com/argpbook/step-by-step-into-argp.pdf
