### ISSUE TITLE
Hi, I was building example when I got this error. I don't know how to deal with this  error, please help me, thanks.

### ISSUE THREAD

**Issue by xiaogao688** [libbpf/libbpf-bootstrap#169]
GEN-SKEL .output/fentry.skel.h
  CC       .output/fentry.o
  BINARY   fentry
  BPF      .output/usdt.bpf.o
libbpf: failed to find BTF info for global/extern symbol 'my_pid'
Error: failed to link '.output/usdt.tmp.bpf.o': No such file or directory (2)
make: *** [Makefile:112：.output/usdt.bpf.o] error 254

**Comment by anakryiko** [comment]
Make sure you have sufficiently new Clang that produces BTF information for global variables. What's your Clang version?

**Comment by JiaoTuan** [comment]
I modified the definition of the global variable in usdt.bpf.c, initialized it with a value of 0, and the compilation passed

**Comment by lei-houjyu** [comment]
> Make sure you have sufficiently new Clang that produces BTF information for global variables. What's your Clang version?

Hi, I'm having the same error. My Clang version is 10.0.0-4ubuntu1. Is it enough?

**Comment by xiaogao688** [comment]
ok，thanks

**Comment by xiaogao688** [comment]
My problem has been solved, thanks for the help
