### ISSUE TITLE
The vmlinux file cannot be found on the system. The vmlinux.h header file cannot be generated

### ISSUE THREAD

**Issue by JeffChong0125** [libbpf/libbpf-bootstrap#172]
Hi, hello, when I was developing based on libbpf, I found that the system could not find the vmlinux file. Without this file, I cannot use bpftool to generate VMlinux. h through vmlinux. I only found the file vmlinuz under /boot. I've looked all over the Internet but haven't found the right way. Can you help me? Here are some of my host information:

loongson@loongson-pc:/$ uname -a

Linux loongson-pc 5.4.18-55-generic #44-KYLINOS SMP Thu Mar 17 09:05:13 UTC 2022 loongarch64 loongarch64 loongarch64 GNU/Linux

**Comment by anakryiko** [comment]
Does your kernel expose /sys/kernel/btf/vmlinux file? You can use that to generate corresponding vmlinux.h file

```
bpftool btf dump file /sys/kernel/btf/vmlinux > vmlinux.h
```

**Comment by JeffChong0125** [comment]
Thank you very much for taking time out of your busy schedule to answer my questions. Well, I can confirm that I did not find the vmlinux file in the whole system. I looked up some materials and found that vmlinux should be generated after some options were set when compiling the kernel. However, the kernel I am using now is a customized Chinese system. I can't get the kernel source code for now? What else can I do

**Comment by anakryiko** [comment]
You'd have to generate BTF from DWARF for your linux image (vmlinux). You can use `pahole --btf_encode_detached=<path-to-generated-btf-output> -J <path-to-vmlinux>`, and then `bpftool btf dump file <path-to-generated-btf-output> > vmlinux.h`

**Comment by anakryiko** [comment]
Yes, vmlinux.h isn't compatible with most other included system headers, it's a known limitation, unfortunately. It's meant to be used as a replacement for UAPI and basic system-wide headers. It will contain all the type definitions you need. It just won't have any constant that is just `#define`-d in the source code. If the constant is defined as an enum, though, it will be exposed through vmlinux.h just fine.

**Comment by anakryiko** [comment]
@liel-almog I'm not sure I fully understand your last question, can you please elaborate?

**Comment by liel-almog** [comment]
How should I use it in production.
I've heard about CO-RE (compile once, run everywhere).
Do I need to generate the file per distro and linux version or I ship a single header for every version.

**Comment by anakryiko** [comment]
@liel-almog normally you'd generate one vmlinux.h file for latest kernel you are supporting (or had at the time of development), and then you'd use BPF CO-RE techniques (https://nakryiko.com/posts/bpf-core-reference-guide/#dealing-with-kernel-changes-and-feature-detection) to deal with any kernel-version incompatibilities.

**Comment by Ashvith10** [comment]
> `bpftool btf dump file /sys/kernel/btf/vmlinux > vmlinux.h`

After this, on inspecting the vmlinux.h file, it doesn't look like it is a compatible header file?

```console
$ bpftool btf dump file /sys/kernel/btf/vmlinux > vmlinux.h 
$ head vmlinux.h
[1] INT 'long unsigned int' size=8 bits_offset=0 nr_bits=64 encoding=(none)
[2] CONST '(anon)' type_id=1
[3] VOLATILE '(anon)' type_id=2
[4] ARRAY '(anon)' type_id=1 index_type_id=21 nr_elems=2
[5] PTR '(anon)' type_id=8
[6] CONST '(anon)' type_id=5
[7] INT 'char' size=1 bits_offset=0 nr_bits=8 encoding=(none)
[8] CONST '(anon)' type_id=7
[9] INT 'unsigned int' size=4 bits_offset=0 nr_bits=32 encoding=(none)
[10] CONST '(anon)' type_id=9
```

Am I doing something wrong here?
