### ISSUE TITLE
Fail to set up performance monitor on a CPU/Core

### ISSUE THREAD

**Issue by try-agaaain** [libbpf/libbpf-bootstrap#173]
When executing the profile executable, the error "Fail to set up performance monitor on a CPU/Core" appears, I am not sure why this error is generated.

My environment:
```console
$ cat /proc/version
Linux version 5.19.0-41-generic (buildd@lcy02-amd64-045) (x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 
GNU ld (GNU Binutils for Ubuntu) 2.38) #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2

$ clang --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

How to reproduce: `cd examples/c && make profile && sudo ./profile`

**Comment by try-agaaain** [comment]
When I compile and run `examples/rust/profile`, I get the following error:
```console
sudo ./profile 
libbpf: prog 'profile': invalid perf event FD -1
libbpf: prog 'profile': invalid perf event FD -1
libbpf: prog 'profile': invalid perf event FD -1
libbpf: prog 'profile': invalid perf event FD -1
libbpf: prog 'profile': invalid perf event FD -1
libbpf: prog 'profile': invalid perf event FD -1
libbpf: prog 'profile': invalid perf event FD -1
libbpf: prog 'profile': invalid perf event FD -1
^C
```

**Comment by tzssangglass** [comment]
> When I compile and run `examples/rust/profile`, I get the following error:

for why: https://github.com/libbpf/libbpf-bootstrap/pull/178#issue-1694421468

**Comment by anakryiko** [comment]
closed by https://github.com/libbpf/libbpf-bootstrap/pull/178

**Comment by wtyfpc** [comment]
I pulled the latest code, but when running it on the virtual machine, it still reports an error. Then I made some modifications:
`//attr.type = PERF_TYPE_HARDWARE;
    attr.type = PERF_TYPE_SOFTWARE;
    attr.size = sizeof(attr);
 //attr.config = PERF_COUNT_HW_CPU_CYCLES;
    attr.config = PERF_COUNT_SW_CPU_CLOCK;`
