### ISSUE TITLE
libbpf: failed to find valid kernel BTF，libbpf: failed to load object 'bootstrap_bpf'，libbpf: failed to load BPF skeleton 'bootstrap_bpf': -3

### ISSUE THREAD

**Issue by JeffChong0125** [libbpf/libbpf-bootstrap#174]
Hi, I had a problem running bootstrap after compiling correctly using the libbpf-bootstrap example: 
[root@localhost c]# ./bootstrap 
libbpf: failed to find valid kernel BTF 
libbpf: Error loading vmlinux BTF: -3 
libbpf: failed to load object 'bootstrap_bpf' 
libbpf: failed to load BPF skeleton 'bootstrap_bpf': -3 
Failed to load and verify BPF skeleton 
I put some specific kernel information in the picture, can you help me to look at this problem? Thanks a million

![image](https://user-images.githubusercontent.com/43671390/235078887-a45665cd-0b6f-4ec9-8039-55f583891a05.png)
![image](https://user-images.githubusercontent.com/43671390/235078912-1af66f90-ab96-40b9-98c9-fb662b5dd936.png)

**Comment by chenhengqi** [comment]
You should turn on `CONFIG_DEBUG_INFO_BTF` or follow instructions on [BTFHub](https://github.com/aquasecurity/btfhub).

**Comment by JeffChong0125** [comment]
> You should turn on `CONFIG_DEBUG_INFO_BTF` or follow instructions on [BTFHub](https://github.com/aquasecurity/btfhub).

I couldn't do that because the distribution appeared to be a custom, non-open source domestic operating system

**Comment by lei-houjyu** [comment]
> You should turn on `CONFIG_DEBUG_INFO_BTF` or follow instructions on [BTFHub](https://github.com/aquasecurity/btfhub).

Hi, would you mind pointing our which doc/page you were referring to? I couldn't find specific instruction about enabling `CONFIG_DEBUG_INFO_BTF`. Thanks!

**Comment by chenhengqi** [comment]
> > You should turn on `CONFIG_DEBUG_INFO_BTF` or follow instructions on [BTFHub](https://github.com/aquasecurity/btfhub).
> 
> Hi, would you mind pointing our which doc/page you were referring to? I couldn't find specific instruction about enabling `CONFIG_DEBUG_INFO_BTF`. Thanks!

https://github.com/iovisor/bcc/blob/master/docs/kernel_config.md
