### ISSUE TITLE
fentry/fexit example breaks when using different syscall 

### ISSUE THREAD

**Issue by laikas123** [libbpf/libbpf-bootstrap#181]
Running the example built from fentry.bpf.c and fentry.c it **works great without any changes made**.

However if I change the lines:

SEC("kprobe/do_unlinkat")
int BPF_KPROBE(do_unlinkat, int dfd, struct filename *name)

to

SEC("kprobe/do_**execve**")
int BPF_KPROBE(do_**execve**, int dfd, struct filename *name)

Then it breaks, and gives:

root@c2eac50ed0ef:/libbpf-bootstrap/examples/c# ./fentry
libbpf: loading object 'fentry_bpf' from buffer
...
...
**libbpf: prog 'do_execve': failed to find kernel BTF type ID of 'do_execve': -3**
libbpf: prog 'do_execve': failed to prepare load attributes: -3
libbpf: prog 'do_execve': failed to load: -3
libbpf: failed to load object 'fentry_bpf'
libbpf: failed to load BPF skeleton 'fentry_bpf': -3
Failed to open BPF skeleton

I know this issue isn't specific to execve, and I know that it's the "SEC" line being changed that is causing issues.

But I don't know how to interpret this error:

"failed to find kernel BTF type ID"

And why does it work for unlinkat, but not execve?

I know this is just my lack of understanding, but I am really lost and any pointers in the right direction would be awesome.

**uname -a output:**

Linux c2eac50ed0ef 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Thank you

**Comment by anakryiko** [comment]
you are probably looking to trace `do_execveat_common` instead?

generally speaking, if you want to trace syscall, I'd recommend using `SEC("ksyscall/<syscallname>")` instead.

**Comment by laikas123** [comment]
@anakryiko thanks so much for the reply. Ah, yes I believe that is what I was looking for. I ended up using "tp/syscalls/..." but I will also check out "kysyscalls".

Closing, and thanks again!
