### ISSUE TITLE
When use bpf_skb_output(), error occurs: [unknown func bpf_skb_output#111]

### ISSUE THREAD

**Issue by xd121614** [libbpf/libbpf-bootstrap#182]
I want to use bpf_skb_output() to share skb with user-space program but met an error when running my test program.

[Code]:
...
struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(key_size, sizeof(int));
    __uint(value_size, sizeof(__u32));
} pb SEC(".maps");

struct event_t *e;
e = bpf_map_lookup_elem(&heap, &zero);
... //fill event_t

bpf_skb_output(skb, &pb, BPF_F_INDEX_MASK, e, sizeof(*e));
...

[error message]:
...
; bpf_skb_output(skb, &pb, BPF_F_INDEX_MASK, e, sizeof(*e));
130: (bf) r1 = r6
131: (18) r2 = 0xffff95ae9f1ea800
133: (18) r3 = 0xffffffff
135: (bf) r4 = r7
136: (b7) r5 = 8228
137: (85) call bpf_skb_output#111
unknown func bpf_skb_output#111
...

**Comment by anakryiko** [comment]
It seems like you are using bpf_skb_output() helper from unsupported BPF program type. Not all program types can use all BPF helpers. this one is networking-specific, so you will need to use one of the networking program types.

**Comment by xd121614** [comment]
> It seems like you are using bpf_skb_output() helper from unsupported BPF program type. Not all program types can use all BPF helpers. this one is networking-specific, so you will need to use one of the networking program types.

Thank you for your reply.I understand.Is there some example for how to use bpf_skb_output in kernel and user space?

**Comment by anakryiko** [comment]
there is one in kernel BPF selftests: https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/progs/kfree_skb.c

**Comment by xd121614** [comment]
Got it.
