### ISSUE TITLE
CLion CMakeList.txt modifications

### ISSUE THREAD

**Issue by unikzforce** [libbpf/libbpf-bootstrap#185]
Hello,

unfortunately I couldn't open up the project properly in `CLion` without adding these two line to the `CMakeList.txt`:

```
include_directories(SYSTEM ${CMAKE_CURRENT_SOURCE_DIR}/../../build)
include_directories(SYSTEM ${CMAKE_CURRENT_SOURCE_DIR}/../../build/libbpf/)
```

may I create a PR for this? I guess they are harmless if i'm not missing anything.

**Comment by anakryiko** [comment]
this looks off, there must be some better way to provide path to headers?
