### ISSUE TITLE
sockfilter

### ISSUE THREAD

**Issue by janeysj** [libbpf/libbpf-bootstrap#188]
I modify the "lo" interface to "eth0", and  build and run sockfilter. Why the SrcIP is always equal to DstIP ? MeanWhile tcpdump can distinguish srcIP and dstIP.

**Comment by JackyYin** [comment]
Hi @janeysj,
I've created a PR to fix this issue: #189.
You could fetch the code in my PR and try again with `./sockfilter -i eth0`.
Thank you!

**Comment by janeysj** [comment]
问题确实解决了，谢谢！你回答得很快呀~ 我应该再思考得深一些
