### ISSUE TITLE
Getting flags from clone3 systemcall using BPF_KPROBE

### ISSUE THREAD

**Issue by sebastiaoamaro** [libbpf/libbpf-bootstrap#200]
Hi everyone, I am trying to retrieve the flags from the clone3 system call which I think will be inside the clone_args structure.
However, I am getting garbage since both parent_tid and flags are not correct values (I run STRACE to know which flags are passed, and use flags & FLAG to check if a certain flag is active), code below.
```
#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
SEC("kprobe/__x64_sys_clone3")
int BPF_KPROBE(__x64_sys_clone3,struct pt_regs *regs)
{

	__u64 pid_tgid = bpf_get_current_pid_tgid();
	__u32 pid = pid_tgid >> 32;
	__u32 tid = (__u32)pid_tgid;

    int THREAD_FLAG = 0x0010000;

	struct clone_args args = {};
	bpf_probe_read(&args, sizeof(args), (void *)PT_REGS_PARM1_CORE(regs));

	__u64 clone_flags = args.flags;
	__u64 parent_tid = args.parent_tid;


	bpf_printk("In clone3 with pid %d \n",parent_tid);

     if ((clone_flags & THREAD_FLAG) != 0){
		  bpf_printk("A thread was created using clone3\n");
	  }
}
```
Does anyone have insights as to why this happens?

**Comment by anakryiko** [comment]
Have you looked at SEC("ksyscall") and BPF_KSYSCALL macro? See https://github.com/libbpf/libbpf-bootstrap/blob/master/examples/c/ksyscall.bpf.c for an example, maybe that will help.

**Comment by sebastiaoamaro** [comment]
Thanks for the reply! need to update my kernel to try BPF_KSYSCALL will do that and comeback with results.

**Comment by anakryiko** [comment]
it's purely libbpf-side thing (both SEC("ksyscall") and BPF_KSYSCALL), it's built on top of normal kprobes. So you shouldn't need upgrading.

**Comment by sebastiaoamaro** [comment]
Hi, thanks for the notice, you are right, I do not need to upgrade.
I got it properly working now with this code, if anyone in the future needs to access something like clone_args:
```
SEC("ksyscall/clone3")
int BPF_KSYSCALL(clone3,struct clone_args *cl_args)
{

	__u64 pid_tgid = bpf_get_current_pid_tgid();
	__u32 pid = pid_tgid >> 32;
	__u32 tid = (__u32)pid_tgid;

    int THREAD_FLAG = 0x0010000;

	__u64 clone_flags;

	struct clone_args clone_args_new;

	bpf_probe_read_user(&clone_args_new, sizeof(clone_args_new), cl_args);


	if ((clone_args_new.flags & THREAD_FLAG)){
		bpf_printk("A thread was created using clone3\n");
	}

        return 0;
}
```
I followed the example from [1] and I think this is correct. Will close the issue since this seems solved.
[1]https://elixir.bootlin.com/linux/latest/source/tools/testing/selftests/bpf/progs/test_probe_user.c#L22

**Comment by anakryiko** [comment]
> Reopening this issue for a quick question is there a bpf_ksyscall equivalent for bpf_kretprobe?

```
SEC("kretsyscall/<syscall>")
int BPF_KRETPROBE(name, int ret) {
   ...
}
```

**Comment by sebastiaoamaro** [comment]
Thanks!
