### ISSUE TITLE
Compilation optimizations cause ebpf verify to fail

### ISSUE THREAD

**Issue by prodigy99** [libbpf/libbpf-bootstrap#204]
In the makefile, the default BPF CODE compilation option is O2 
![image](https://github.com/libbpf/libbpf-bootstrap/assets/42128890/449305a7-2d4c-4d18-a213-815c3814f328)
, but this may cause ebpf verify to fail due to code optimization, such as the following code:
![image](https://github.com/libbpf/libbpf-bootstrap/assets/42128890/e829ccb1-59a2-4037-94c3-19f7ecf4d662)
In the above code, the maximum length of the &bt->buf array is MAX_BUFFER_SIZE, and I have ensured in the above judgment statement that size+*offset will be strictly less than MAX_BUFFER_SIZE, but at the -O2 compile level, This code will cause ebpf verify to report an error :
>; if (*offset + MAX_ARGS_SIZE >= MAX_BUFFER_SIZE) {
84: (69) r2 = *(u16 *)(r9 +0)
 R0=map_value(id=0,off=0,ks=4,vs=2,imm=0) R6=mem(id=0,ref_obj_id=7,off=0,imm=0) R7=invP0 R8=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R9_w=map_value(id=0,off=0,ks=4,vs=2,imm=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=invP fp-32=ptr_ fp-40=mmmmmmmm refs=7
85: (b7) r1 = 31744
; if (*offset + MAX_ARGS_SIZE >= MAX_BUFFER_SIZE) {
86: (2d) if r1 > r2 goto pc+2
 R0=map_value(id=0,off=0,ks=4,vs=2,imm=0) R1_w=invP31744 R2_w=invP(id=0,umin_value=31744,umax_value=65535,var_off=(0x0; 0xffff)) R6=mem(id=0,ref_obj_id=7,off=0,imm=0) R7=invP0 R8=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R9_w=map_value(id=0,off=0,ks=4,vs=2,imm=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=invP fp-32=ptr_ fp-40=mmmmmmmm refs=7
87: (b7) r2 = 0
; *offset = 0;
88: (6b) *(u16 *)(r9 +0) = r2
 R0=map_value(id=0,off=0,ks=4,vs=2,imm=0) R1_w=invP31744 R2_w=invP0 R6=mem(id=0,ref_obj_id=7,off=0,imm=0) R7=invP0 R8=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R9_w=map_value(id=0,off=0,ks=4,vs=2,imm=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=invP fp-32=ptr_ fp-40=mmmmmmmm refs=7
; bpf_probe_read(&bt->buf[*offset], size, data);
89: (bf) r1 = r8
90: (0f) r1 += r2
91: (bf) r3 = r10
; 
92: (07) r3 += -4
; bpf_probe_read(&bt->buf[*offset], size, data);
93: (b7) r2 = 2
94: (85) call bpf_probe_read#4
 R0=map_value(id=0,off=0,ks=4,vs=2,imm=0) R1_w=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R2_w=invP2 R3_w=fp-4 R6=mem(id=0,ref_obj_id=7,off=0,imm=0) R7=invP0 R8=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R9_w=map_value(id=0,off=0,ks=4,vs=2,imm=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=invP fp-32=ptr_ fp-40=mmmmmmmm refs=7
; *offset += size;
95: (69) r2 = *(u16 *)(r9 +0)
 R0=invP(id=0) R6=mem(id=0,ref_obj_id=7,off=0,imm=0) R7=invP0 R8=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R9=map_value(id=0,off=0,ks=4,vs=2,imm=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=invP fp-32=ptr_ fp-40=mmmmmmmm refs=7
96: (07) r2 += 2
97: (bf) r3 = r2
98: (57) r3 &= 65535
99: (b7) r1 = 0
; if (*offset + MAX_ARGS_SIZE >= MAX_BUFFER_SIZE) {
100: (25) if r3 > 0x7bff goto pc+1
 R0=invP(id=0) R1_w=invP0 R2_w=invP(id=11,umin_value=2,umax_value=65537,var_off=(0x0; 0x1ffff)) R3_w=invP(id=0,umax_value=31743,var_off=(0x0; 0x7fff)) R6=mem(id=0,ref_obj_id=7,off=0,imm=0) R7=invP0 R8=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R9=map_value(id=0,off=0,ks=4,vs=2,imm=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=invP fp-32=ptr_ fp-40=mmmmmmmm refs=7
101: (bf) r1 = r2
; 
102: (6b) *(u16 *)(r9 +0) = r1
 R0=invP(id=0) R1_w=invP(id=11,umin_value=2,umax_value=65537,var_off=(0x0; 0x1ffff)) R2_w=invP(id=11,umin_value=2,umax_value=65537,var_off=(0x0; 0x1ffff)) R3_w=invP(id=0,umax_value=31743,var_off=(0x0; 0x7fff)) R6=mem(id=0,ref_obj_id=7,off=0,imm=0) R7=invP0 R8=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R9=map_value(id=0,off=0,ks=4,vs=2,imm=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=invP fp-32=ptr_ fp-40=mmmmmmmm refs=7
; write_to_bufs(bt, data, arg_size, offset);
103: (69) r7 = *(u16 *)(r10 -4)
; if (size > MAX_ARGS_SIZE)
104: (25) if r7 > 0x400 goto pc+9
 R0=invP(id=0) R1_w=invP(id=11,umin_value=2,umax_value=65537,var_off=(0x0; 0x1ffff)) R2_w=invP(id=11,umin_value=2,umax_value=65537,var_off=(0x0; 0x1ffff)) R3_w=invP(id=0,umax_value=31743,var_off=(0x0; 0x7fff)) R6=mem(id=0,ref_obj_id=7,off=0,imm=0) R7_w=invP(id=0,umax_value=1024,var_off=(0x0; 0x7ff)) R8=map_value(id=0,off=0,ks=4,vs=32768,imm=0) R9=map_value(id=0,off=0,ks=4,vs=2,imm=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=invP fp-32=ptr_ fp-40=mmmmmmmm refs=7
; bpf_probe_read(&bt->buf[*offset], size, data);
105: (57) r1 &= 65535
106: (0f) r8 += r1
; bpf_probe_read(&bt->buf[*offset], size, data);
107: (bf) r1 = r8
108: (bf) r2 = r7
109: (79) r3 = *(u64 *)(r10 -40)
110: (85) call bpf_probe_read#4
 R0=invP(id=0) R1_w=map_value(id=0,off=0,ks=4,vs=32768,umax_value=65535,var_off=(0x0; 0xffff)) R2_w=invP(id=12,umax_value=1024,var_off=(0x0; 0x7ff)) R3_w=invP(id=0) R6=mem(id=0,ref_obj_id=7,off=0,imm=0) R7_w=invP(id=12,umax_value=1024,var_off=(0x0; 0x7ff)) R8_w=map_value(id=0,off=0,ks=4,vs=32768,umax_value=65535,var_off=(0x0; 0xffff)) R9=map_value(id=0,off=0,ks=4,vs=2,imm=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=invP fp-32=ptr_ fp-40=mmmmmmmm refs=7
invalid access to map value, value_size=32768 off=65535 size=0
R1 max value is outside of the allowed memory range
processed 235 insns (limit 1000000) max_states_per_insn 1 total_states 20 peak_states 20 mark_read 16
-- END PROG LOAD LOG --
libbpf: prog '__x64_sys_openat': failed to load: -13
libbpf: failed to load object 'tracer_bpf'
libbpf: failed to load BPF skeleton 'tracer_bpf': -13
Failed to load and verify BPF skeleton

But at the -o1 compile level, this code works fine.In fact, the above code is a version of many versions I have tried to simplify, before this, I wrote some complex judgment logic to achieve some more complex functions, but always for some inexplicable reason there are strange errors. There is even some code that would have passed bpf verify, but adding a line of output code will cause bpf verify to fail. This has been bothering me for a long time, and I wonder if this problem can be solved by modifying the makefile file to reduce compiler optimization, or if it requires compliance with some development best practices？

Here are some related configurations:
llvm version：18.0 
Linux version : Ubuntu server 22.04.2

**Comment by danielocfb** [comment]
It's a generally recognized (in the BPF community) problem. To quote Alexei Starovoitov:

> we brought this issue [the brittle nature of optimizations in conjunction with the verifier] to llvm folks many times. Unfortunately to deaf ears. GCC folks are more accommodating. The plan is to have -Overifiable flag that will turn off optimizations that lose information. Once GCC leads the way  maybe clang folks will start listening. afaik llvm community lost a bunch of great engineers to AI projects and that shows.

**Comment by prodigy99** [comment]
> It's a generally recognized (in the BPF community) problem. To quote Alexei Starovoitov:
> 
> > we brought this issue [the brittle nature of optimizations in conjunction with the verifier] to llvm folks many times. Unfortunately to deaf ears. GCC folks are more accommodating. The plan is to have -Overifiable flag that will turn off optimizations that lose information. Once GCC leads the way  maybe clang folks will start listening. afaik llvm community lost a bunch of great engineers to AI projects and that shows.

Are there any best practices to avoid these problems as much as possible? I tried to look for this information on the Internet, but I couldn't find it.

**Comment by anakryiko** [comment]
try storing `*offset` result in local variable and then check that it is within correct range. And then use that local variable instead of dereferencing `*offset` again in `bt->buf[*offset]`
