### ISSUE TITLE
ksyscall invalid func unknown#177

### ISSUE THREAD

**Issue by sir997** [libbpf/libbpf-bootstrap#206]
This issue occurred when i run example/c ksyscall, and other prog(minimal, kprobe, fentry etc..) are successful.

$ uname -a
Linux VM-248-84-tencentos 5.4.119-19.0009.32 #1 SMP Sun Jul 16 17:52:11 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

$ make clean && make ksyscall

$ ./ksyscall
libbpf: loading object 'ksyscall_bpf' from buffer
libbpf: elf: section(2) .symtab, size 408, link 1, flags 0, type=2
libbpf: elf: section(3) ksyscall/tgkill, size 672, link 0, flags 6, type=1
libbpf: sec 'ksyscall/tgkill': found program 'tgkill_entry' at insn offset 0 (0 bytes), code size 84 insns (672 bytes)
libbpf: elf: section(4) ksyscall/kill, size 456, link 0, flags 6, type=1
libbpf: sec 'ksyscall/kill': found program 'entry_probe' at insn offset 0 (0 bytes), code size 57 insns (456 bytes)
libbpf: elf: section(5) license, size 4, link 0, flags 3, type=1
libbpf: license of ksyscall_bpf is GPL
libbpf: elf: section(6) .rodata, size 143, link 0, flags 2, type=1
libbpf: elf: section(7) .relksyscall/tgkill, size 32, link 2, flags 40, type=9
libbpf: elf: section(8) .relksyscall/kill, size 32, link 2, flags 40, type=9
libbpf: elf: section(9) .BTF, size 1262, link 0, flags 0, type=1
libbpf: elf: section(10) .BTF.ext, size 924, link 0, flags 0, type=1
libbpf: looking for externs among 17 symbols...
libbpf: collected 1 externs total
libbpf: extern (kcfg) #0: symbol 14, off 0, name LINUX_HAS_SYSCALL_WRAPPER
libbpf: map 'ksyscall.rodata' (global data): at sec_idx 6, offset 0, flags 80.
libbpf: map 0 is "ksyscall.rodata"
libbpf: map 'ksyscal.kconfig' (global data): at sec_idx 2, offset 0, flags 480.
libbpf: map 1 is "ksyscal.kconfig"
libbpf: sec '.relksyscall/tgkill': collecting relocation for section(3) 'ksyscall/tgkill'
libbpf: sec '.relksyscall/tgkill': relo #0: insn #0 against 'LINUX_HAS_SYSCALL_WRAPPER'
libbpf: prog 'tgkill_entry': found extern #0 'LINUX_HAS_SYSCALL_WRAPPER' (sym 14) for insn #0
libbpf: sec '.relksyscall/tgkill': relo #1: insn #77 against '.rodata'
libbpf: prog 'tgkill_entry': found data map 0 (ksyscall.rodata, sec 6, off 0) for insn 77
libbpf: sec '.relksyscall/kill': collecting relocation for section(4) 'ksyscall/kill'
libbpf: sec '.relksyscall/kill': relo #0: insn #0 against 'LINUX_HAS_SYSCALL_WRAPPER'
libbpf: prog 'entry_probe': found extern #0 'LINUX_HAS_SYSCALL_WRAPPER' (sym 14) for insn #0
libbpf: sec '.relksyscall/kill': relo #1: insn #50 against '.rodata'
libbpf: prog 'entry_probe': found data map 0 (ksyscall.rodata, sec 6, off 0) for insn 50
libbpf: loading kernel BTF '/sys/kernel/btf/vmlinux': 0
libbpf: extern (kcfg) 'LINUX_HAS_SYSCALL_WRAPPER': set to 0x1
libbpf: map 'ksyscall.rodata': created successfully, fd=4
libbpf: map 'ksyscal.kconfig': created successfully, fd=5
libbpf: sec 'ksyscall/tgkill': found 7 CO-RE relocations
libbpf: CO-RE relocating [2] struct pt_regs: found target candidate [193] struct pt_regs in [vmlinux]
libbpf: prog 'tgkill_entry': relo #0: <byte_off> [2] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'tgkill_entry': relo #0: matching candidate #0 <byte_off> [193] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'tgkill_entry': relo #0: patched insn #4 (ALU/ALU64) imm 112 -> 112
libbpf: prog 'tgkill_entry': relo #1: <byte_off> [2] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'tgkill_entry': relo #1: matching candidate #0 <byte_off> [193] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'tgkill_entry': relo #1: patched insn #5 (LDX/ST/STX) off 112 -> 112
libbpf: prog 'tgkill_entry': relo #2: <byte_off> [2] struct pt_regs.si (0:13 @ offset 104)
libbpf: prog 'tgkill_entry': relo #2: matching candidate #0 <byte_off> [193] struct pt_regs.si (0:13 @ offset 104)
libbpf: prog 'tgkill_entry': relo #2: patched insn #12 (ALU/ALU64) imm 104 -> 104
libbpf: prog 'tgkill_entry': relo #3: <byte_off> [2] struct pt_regs.dx (0:12 @ offset 96)
libbpf: prog 'tgkill_entry': relo #3: matching candidate #0 <byte_off> [193] struct pt_regs.dx (0:12 @ offset 96)
libbpf: prog 'tgkill_entry': relo #3: patched insn #20 (ALU/ALU64) imm 96 -> 96
libbpf: prog 'tgkill_entry': relo #4: <byte_off> [2] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'tgkill_entry': relo #4: matching candidate #0 <byte_off> [193] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'tgkill_entry': relo #4: patched insn #49 (LDX/ST/STX) off 112 -> 112
libbpf: prog 'tgkill_entry': relo #5: <byte_off> [2] struct pt_regs.si (0:13 @ offset 104)
libbpf: prog 'tgkill_entry': relo #5: matching candidate #0 <byte_off> [193] struct pt_regs.si (0:13 @ offset 104)
libbpf: prog 'tgkill_entry': relo #5: patched insn #50 (LDX/ST/STX) off 104 -> 104
libbpf: prog 'tgkill_entry': relo #6: <byte_off> [2] struct pt_regs.dx (0:12 @ offset 96)
libbpf: prog 'tgkill_entry': relo #6: matching candidate #0 <byte_off> [193] struct pt_regs.dx (0:12 @ offset 96)
libbpf: prog 'tgkill_entry': relo #6: patched insn #51 (LDX/ST/STX) off 96 -> 96
libbpf: sec 'ksyscall/kill': found 5 CO-RE relocations
libbpf: prog 'entry_probe': relo #0: <byte_off> [2] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'entry_probe': relo #0: matching candidate #0 <byte_off> [193] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'entry_probe': relo #0: patched insn #4 (ALU/ALU64) imm 112 -> 112
libbpf: prog 'entry_probe': relo #1: <byte_off> [2] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'entry_probe': relo #1: matching candidate #0 <byte_off> [193] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'entry_probe': relo #1: patched insn #5 (LDX/ST/STX) off 112 -> 112
libbpf: prog 'entry_probe': relo #2: <byte_off> [2] struct pt_regs.si (0:13 @ offset 104)
libbpf: prog 'entry_probe': relo #2: matching candidate #0 <byte_off> [193] struct pt_regs.si (0:13 @ offset 104)
libbpf: prog 'entry_probe': relo #2: patched insn #12 (ALU/ALU64) imm 104 -> 104
libbpf: prog 'entry_probe': relo #3: <byte_off> [2] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'entry_probe': relo #3: matching candidate #0 <byte_off> [193] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'entry_probe': relo #3: patched insn #27 (LDX/ST/STX) off 112 -> 112
libbpf: prog 'entry_probe': relo #4: <byte_off> [2] struct pt_regs.si (0:13 @ offset 104)
libbpf: prog 'entry_probe': relo #4: matching candidate #0 <byte_off> [193] struct pt_regs.si (0:13 @ offset 104)
libbpf: prog 'entry_probe': relo #4: patched insn #28 (LDX/ST/STX) off 104 -> 104
libbpf: prog 'tgkill_entry': BPF program load failed: Invalid argument
libbpf: prog 'tgkill_entry': -- BEGIN PROG LOAD LOG --
Unrecognized arg#0 type PTR
; int BPF_KSYSCALL(tgkill_entry, pid_t tgid, pid_t tid, int sig)
0: (18) r2 = 0xffffc900002c0000
2: (71) r2 = *(u8 *)(r2 +0)
 R1=ctx(id=0,off=0,imm=0) R2_w=map_value(id=0,off=0,ks=4,vs=1,imm=0) R10=fp0
3: (15) if r2 == 0x0 goto pc+45
last_idx 3 first_idx 0
regs=4 stack=0 before 2: (71) r2 = *(u8 *)(r2 +0)
4: (b7) r2 = 112
5: (79) r6 = *(u64 *)(r1 +112)
6: (bf) r3 = r6
7: (0f) r3 += r2
8: (bf) r1 = r10
9: (07) r1 += -56
; int BPF_KSYSCALL(tgkill_entry, pid_t tgid, pid_t tid, int sig)
10: (b7) r2 = 8
11: (85) call bpf_probe_read_kernel#113
last_idx 11 first_idx 0
regs=4 stack=0 before 10: (b7) r2 = 8
12: (b7) r1 = 104
13: (bf) r3 = r6
14: (0f) r3 += r1
; int BPF_KSYSCALL(tgkill_entry, pid_t tgid, pid_t tid, int sig)
15: (79) r8 = *(u64 *)(r10 -56)
16: (bf) r1 = r10
; int BPF_KSYSCALL(tgkill_entry, pid_t tgid, pid_t tid, int sig)
17: (07) r1 += -56
; int BPF_KSYSCALL(tgkill_entry, pid_t tgid, pid_t tid, int sig)
18: (b7) r2 = 8
19: (85) call bpf_probe_read_kernel#113
last_idx 19 first_idx 12
regs=4 stack=0 before 18: (b7) r2 = 8
20: (b7) r1 = 96
21: (0f) r6 += r1
; int BPF_KSYSCALL(tgkill_entry, pid_t tgid, pid_t tid, int sig)
22: (79) r9 = *(u64 *)(r10 -56)
23: (bf) r1 = r10
; int BPF_KSYSCALL(tgkill_entry, pid_t tgid, pid_t tid, int sig)
24: (07) r1 += -56
; int BPF_KSYSCALL(tgkill_entry, pid_t tgid, pid_t tid, int sig)
25: (b7) r2 = 8
26: (bf) r3 = r6
27: (85) call bpf_probe_read_kernel#113
last_idx 27 first_idx 12
regs=4 stack=0 before 26: (bf) r3 = r6
regs=4 stack=0 before 25: (b7) r2 = 8
; int BPF_KSYSCALL(tgkill_entry, pid_t tgid, pid_t tid, int sig)
28: (79) r7 = *(u64 *)(r10 -56)
; __u32 caller_pid = bpf_get_current_pid_tgid() >> 32;
29: (85) call bpf_get_current_pid_tgid#14
30: (bf) r6 = r0
; 
31: (67) r7 <<= 32
32: (77) r7 >>= 32
; if (sig == 0) {
33: (15) if r7 == 0x0 goto pc+48
 R0_w=inv(id=0) R6_w=inv(id=0) R7_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=0) R9=inv(id=0) R10=fp0 fp-56=mmmmmmmm
34: (bf) r1 = r10
; 
35: (07) r1 += -16
; bpf_get_current_comm(&comm, sizeof(comm));
36: (7b) *(u64 *)(r10 -64) = r1
37: (b7) r2 = 16
38: (85) call bpf_get_current_comm#16
last_idx 38 first_idx 28
regs=4 stack=0 before 37: (b7) r2 = 16
; bpf_printk(
39: (67) r7 <<= 32
40: (c7) r7 s>>= 32
41: (7b) *(u64 *)(r10 -24) = r7
42: (67) r8 <<= 32
43: (c7) r8 s>>= 32
44: (7b) *(u64 *)(r10 -32) = r8
45: (67) r9 <<= 32
46: (c7) r9 s>>= 32
47: (7b) *(u64 *)(r10 -40) = r9
48: (05) goto pc+22
; 
71: (79) r1 = *(u64 *)(r10 -64)
72: (7b) *(u64 *)(r10 -48) = r1
73: (77) r6 >>= 32
74: (7b) *(u64 *)(r10 -56) = r6
75: (bf) r3 = r10
76: (07) r3 += -56
77: (18) r1 = 0xffff8881344ee510
79: (b7) r2 = 81
80: (b7) r4 = 40
81: (85) call unknown#177
invalid func unknown#177
processed 58 insns (limit 1000000) max_states_per_insn 0 total_states 3 peak_states 3 mark_read 2
-- END PROG LOAD LOG --
libbpf: prog 'tgkill_entry': failed to load: -22
libbpf: failed to load object 'ksyscall_bpf'
libbpf: failed to load BPF skeleton 'ksyscall_bpf': -22
Failed to open BPF skeleton

**Comment by anakryiko** [comment]
`invalid func unknown#177` is actually an error. This is `bpf_trace_vprintk()` which your kernel doesn't know about, because it's a bit older.

To make it work locally you can split or simplify those `bpf_printk()` calls to pass at most 3 arguments. Or update the kernel.

**Comment by sir997** [comment]
> `invalid func unknown#177` is actually an error. This is `bpf_trace_vprintk()` which your kernel doesn't know about, because it's a bit older.
> 
> To make it work locally you can split or simplify those `bpf_printk()` calls to pass at most 3 arguments. Or update the kernel.

Thanks a lot for your assistance! It was a big help.
