### ISSUE TITLE
libbpf: Error in bpf_create_map_xattr():Invalid argument(-22). Retrying without BTF

### ISSUE THREAD

**Issue by hundredmiles** [libbpf/libbpf-bootstrap#209]
BPF_MAP_TYPE_ARRAY seems not to work when either of the key or value is a user-defined type

```
#define MAX_ENTRIES_FLOW            1

// does not work
struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __type(key, struct network_tuple);
    __type(value, struct syn_event);
    __uint(max_entries, MAX_ENTRIES_FLOW);
} flow_table SEC(".maps");


// works
struct {
     __uint(type, BPF_MAP_TYPE_ARRAY);
     __type(key, __u32);
     __type(value, __u32);
     __uint(max_entries, MAX_ENTRIES_FLOW);
} flow_table SEC(".maps");
```

```
The output when trying to run the code:
libbpf: Error in bpf_create_map_xattr(flow_table):Invalid argument(-22). Retrying without BTF.
libbpf: map 'flow_table': failed to create: Invalid argument(-22)
libbpf: failed to load object 'tp_bpf'
libbpf: failed to load BPF skeleton 'tp_bpf': -22
```

Also, as opposed to the comment in the [minimal_legacy.bpf.c](https://github.com/libbpf/libbpf-bootstrap/blob/master/examples/c/minimal_legacy.bpf.c) "Create an array with 1 entry instead of a global variable which does not work with older kernels", with the key and value as __u32 more than 1 max_entries work, but with key and value as network_tuple and syn_event, it does not work even with max_entries equal to 1.

Any solution for this?

**Comment by anakryiko** [comment]
ARRAY map needs to have 4-byte sized integer key. I suspect your `struct network_tuple` is not 4 bytes sized, right? Perhaps you meant HASH map?

**Comment by hundredmiles** [comment]
Yes, that's correct. Checked in the [kernel docs](https://docs.kernel.org/bpf/map_array.html) as well. HASH map is the right type for my case.
