### ISSUE TITLE
profile can't output full user stack trace

### ISSUE THREAD

**Issue by sealindx** [libbpf/libbpf-bootstrap#212]
I can run the profile demo on the virtual machine，But in the stack information, there is no symbol information such as printing functions.
```
COMM: lua (pid=22507)  CPU 1
No Kernel Stack
Userspace:
 0 [<fffffffffffffe00>]
 1 [<00005570db739fdo>] luaV execute+0x21fo lvm.c:1295
 2 [<00005570dc8e5990>]
 3 [<0000000000000046>]
 4 [<0000000000011006>]
 5 [<237381d808001004>]
 6 [<d9a9e5f803002404>]
 7 [<4df50ff307002404>]
 8 [<572793a509002404>]
 9 [<00000000013f2405>]
10 [<42e57d940e002404>]
11 [<47e544a609002404>]
12 [<8e46ab540a002404>]
13 [<2dof2ce108002404>]
14 [<7afd477d07002404>]
15 [<7b4aed060c002404>]
16 [<fgaba49e09002404>]
17 [<95ca1c320b002404>]
18 [<8e46aba80a002404>]
```

**Comment by danielocfb** [comment]
Symbolization is best-effort. If the binary is stripped and no DWARF information can be discovered, there is nothing we can do. Please check that the binary in question has symbols preserved.

**Comment by anakryiko** [comment]
these addresses also don't look like user-space addresses. It might be that your application is compiled without frame pointers enabled, so captured stack traces will be invalid. You might want to look into -fno-omit-frame-pointer compiler option.
