### ISSUE TITLE
Dropping Ethernet packets to user space applications

### ISSUE THREAD

**Issue by venkatmakam** [libbpf/libbpf-bootstrap#213]
we are trying to drop the Ethernet packets on wlan0 reaching all user space application. 
we modified sockfilter.bpf.c code to drop all the frames as shown in following code snippets.
`SEC("socket")
int filter(struct __sk_buff *skb) {
   return BPF_DROP;
}`

`SEC("socket")
int filter(struct __sk_buff *skb) {
   return 0;
}`

But still see the packets are reaching to netstat and also to browser.Our understanding is, it should be possible for 
ebpf to drop the packets at system level. 
Can you please suggest if we are missing anything in the code?

**Environments:**
Device 1:
raspberry pi 4 with kernel 6.1.46-v8+
clang version 13.0.1-6~deb11u1

Device 2:
x86 PC with kernel 5.15
clang version 14

Note:
The application is **not running** in docker

**Comment by anakryiko** [comment]
this is probably not the right place to ask such question. You will find a better support either on bpf mailing list (bpf@vger.kernel.org) or asking on Stackoverflow or maybe Cilium slack channels.

This repo is mostly to demonstrate basic BPF usage together with libbpf. Thanks for understanding.
