### ISSUE TITLE
Retrieving argument values from newfstatat

### ISSUE THREAD

**Issue by sebastiaoamaro** [libbpf/libbpf-bootstrap#219]
Hi, I am trying to retrieve the argument values from the newfstatat syscall, this is the code I am currently running,

```
SEC("ksyscall/newfstatat")
int BPF_KPROBE(__x64_sys_newfstatat,int dfd,char* filename)

{	
	int new_dfd;

	int err_dfd = bpf_probe_read_user(&new_dfd, sizeof(new_dfd), dfd);

	const char path[64];

	int err = bpf_probe_read_user_str(&path,sizeof(path),filename);

	bpf_printk("Looking at a newfstatat for %d err is %d and path is %s and err is %d\n",dfd,err_dfd,path,err);
}
```
The output from this is 
```
systemd-oomd-632     [006] d..31  8848.968158: bpf_trace_printk: Looking at a newfstatat for 0 err is -14 and path is  and err is -14
```

The -14 error is the "Bad Address" error number, however, I am using both bpf_probe_read_user and bpf_probe_read_user_str, which as far as I am aware should retrieve the correct values, I previously used syscall in clone3 to do this same thing in a successful fashion.

Any ideas as to why this is happening?

**Comment by anakryiko** [comment]
-14 is EFAULT, which is returned when memory address is invalid, but also when that memory is not mapped into RAM (e.g., it could be in the swap or mapped to file page that wasn't mapped yet). This is the limitation of bpf_probe_read_user(). Search for "sleepable BPF program" and see if you can use that. It allows to read memory even if it wasn't paged in (through a different helper).

**Comment by sebastiaoamaro** [comment]
> -14 is EFAULT, which is returned when memory address is invalid, but also when that memory is not mapped into RAM (e.g., it could be in the swap or mapped to file page that wasn't mapped yet). This is the limitation of bpf_probe_read_user(). Search for "sleepable BPF program" and see if you can use that. It allows to read memory even if it wasn't paged in (through a different helper).

Just a heads up to whoever reads this, the BPF sleepable flag is not available for kprobes. 
https://elixir.bootlin.com/linux/latest/source/tools/testing/selftests/bpf/prog_tests/attach_probe.c#L253
