### ISSUE TITLE
Rust: How to attach a single bpf program to multiple network interfaces?

### ISSUE THREAD

**Issue by unikzforce** [libbpf/libbpf-bootstrap#220]
Hey, 

how can i attach a xdp program to multiple network interfaces simultaneously?

this code is incorrect cause the the last network interface would be attached properly, not previous ones:

![image](https://github.com/libbpf/libbpf-bootstrap/assets/7010566/0428643a-1a00-4534-98cb-344314a47009)

**Comment by unikzforce** [comment]
do i need to create independent skels for each interface?

**Comment by anakryiko** [comment]
if you are attaching same BPF program to multiple network interfaces, you'll just need to store returned links somewhere outside the skeleton. Skeleton's links container is just a convenience, you don't have to use it. cc @danielocfb

**Comment by unikzforce** [comment]
@anakryiko i'm adding it to a vector, but this time nothing is being attached to no network interface
![image](https://github.com/libbpf/libbpf-bootstrap/assets/7010566/cbea5798-d234-4f10-9534-3ea6590aff02)

**Comment by unikzforce** [comment]
Aah thanks a lot , i've just collected them into a vector and now it is working fine, closing.
