### ISSUE TITLE
Android xmake fails

### ISSUE THREAD

**Issue by ghost** [libbpf/libbpf-bootstrap#228]
System: `Ubuntu 22.04, Kernel 5.15.0-86-generic`

I run same code what's shown in the readme:

```
$ git submodule update --init --recursive       # check out libbpf
$ cd examples/c
$ xmake f -p android
$ xmake
```

Err:
```
[ 12%]: compiling.bpf uprobe.bpf.c
[ 12%]: compiling.bpf fentry.bpf.c
[ 17%]: cache compiling.release ../../libbpf/src/relo_core.c
[ 17%]: cache compiling.release ../../libbpf/src/gen_loader.c
[ 19%]: cache compiling.release ../../libbpf/src/bpf.c
[ 19%]: cache compiling.release ../../libbpf/src/ringbuf.c
[ 21%]: cache compiling.release ../../libbpf/src/linker.c
[ 27%]: cache compiling.release ../../libbpf/src/btf.c
[ 31%]: cache compiling.release ../../libbpf/src/usdt.c
[ 31%]: cache compiling.release ../../libbpf/src/libbpf.c
[ 31%]: cache compiling.release ../../libbpf/src/zip.c
[ 31%]: cache compiling.release ../../libbpf/src/netlink.c
[ 31%]: cache compiling.release ../../libbpf/src/btf_dump.c
[ 31%]: cache compiling.release ../../libbpf/src/elf.c
[ 31%]: compiling.bpf bootstrap.bpf.c


error: ../../libbpf/src/elf.c:138:39: error: use of undeclared identifier 'SHT_GNU_versym'
        scn = elf_find_next_scn_by_type(elf, SHT_GNU_versym, NULL);
                                             ^
../../libbpf/src/elf.c:143:39: error: use of undeclared identifier 'SHT_GNU_verdef'
        scn = elf_find_next_scn_by_type(elf, SHT_GNU_verdef, NULL);
                                             ^
2 errors generated.
  > in ../../libbpf/src/elf.c

```

P.S. there should a tests at least for cases mentioned within the readme file :/

**Comment by anakryiko** [comment]
xmake support is best-effort, unfortunately. It seems like your libelf is too old, unfortunately. Can you try updating it on your system?

**Comment by anakryiko** [comment]
actually, I think we might need to just fix it on libbpf side to avoid this problem, I'll look into that

**Comment by anakryiko** [comment]
hm... it seems like `SHT_GNU_versym` has been defined since at least 2005, so either you have super ancient version of libelf, or it's wrong one. You need elfutils package, I believe.

**Comment by guri87-byte** [comment]
I have the same case as the OP, when running `xmake f -p android` on the first time following packages are installed:
```
  -> ndk 22.0
  -> zlib v1.3 [toolchains:"@ndk", from:elfutils]
  -> libintl 0.21 [toolchains:"@ndk", from:elfutils]
  -> argp-standalone 1.3 [toolchains:"@ndk", from:elfutils]
  -> elfutils 0.183
```
It installed elfutils 0.183, I guess we all should have the same version, isn't?

`dpkg -s libelf1`

```
Package: libelf1
Status: install ok installed
Priority: important
Section: libs
Installed-Size: 192
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: elfutils
Version: 0.186-1build1
Depends: libc6 (>= 2.33), zlib1g (>= 1:1.1.4)
```

**Comment by guri87-byte** [comment]
Updated to the latest `elfutils` available on Ubuntu 22.04 but same.

**Comment by waruqi** [comment]
I have fixed this issue, see this patch. https://github.com/libbpf/libbpf-bootstrap/pull/236

This is because after the elfutils package in xmake-repo was installed, its make install script did not automatically install elf.h, so elfutils/libelf.h automatically found elf.h on the system, resulting in some header file conflicts.

I've fixed this, try reinstalling the elfutils package to fix this.

```console
xrepo update-repo
xrepo remove --all -y elfutils
xmake f -p android -c --require-bpftool=y
xmake
```

**Comment by guri87-byte** [comment]
When I do `--require-bpftool=y` which means that bpftool is fetched from xmake repo it works! thanks!
But when I try to install `bfptool` from Github on the system, for example latest 7.2.0 it fails same way.

I need to be able to specify package versions by commit or something

**Comment by waruqi** [comment]
> When I do `--require-bpftool=y` which means that bpftool is fetched from xmake repo it works! thanks! But when I try to install `bfptool` from Github on the system, for example latest 7.2.0 it fails same way.
> 
> I need to be able to specify package versions by commit or something

Due to some issues with system bpftool 7.2.0, it is recommended to pull the specified version of bpftool from the remote by default until these issues are fixed. It always works fine.

Also, we can specify the bpftool version in the `add_requires()` of xmake.lua

https://github.com/libbpf/libbpf-bootstrap/pull/237

**Comment by guri87-byte** [comment]
Sounds good, thank you!

**Comment by waruqi** [comment]
> libbpf: map 'my_pid_map': unsupported map linkage static.
Error: failed to open BPF object file: Operation not supported

Only the minimal_legacy example has this problem, perhaps the latest bpftool 7.2.0 no longer supports it.

```c
/* Create an array with 1 entry instead of a global variable
 * which does not work with older kernels */
struct {
	__uint(type, BPF_MAP_TYPE_ARRAY);
	__uint(max_entries, 1);
	__type(key, u32);
	__type(value, pid_t);
} my_pid_map SEC(".maps");
```

>  does not work with older kernels

**Comment by waruqi** [comment]
I have fixed this error. https://github.com/libbpf/libbpf-bootstrap/pull/237

we can use bpftool 7.2.0 now.

**Comment by guri87-byte** [comment]
Wow, great. Thanks @waruqi 

One more question, why we not able to use vendor provided similar to how `libbpf` is used within `xmake.lua`
