### ISSUE TITLE
add xdp synproxy in c example?

### ISSUE THREAD

**Issue by vincentmli** [libbpf/libbpf-bootstrap#229]
Hi @anakryiko 

I have ported xdp synproxy in kernel bpf selftest to libbpf-bootstrap repo as a learning process for myself, also added static tail calls to chain multiple XDP program together, would you take such XDP program as c examples? [xdp example](https://github.com/vincentmli/libbpf-bootstrap/blob/dnsrrl/examples/c/xdppacket.bpf.c). it is a practical example :)

**Comment by anakryiko** [comment]
TBH, it seems a bit too big and complicated to be just a simple example of how to use XDP. Perhaps  check if https://github.com/xdp-project/xdp-tools has some examples like that and contribute to that XDP-specific project?

**Comment by vincentmli** [comment]
ok got it
