### ISSUE TITLE
[Android] Failed to find valid kernel BTF

### ISSUE THREAD

**Issue by zebede22** [libbpf/libbpf-bootstrap#250]
Device: Android 13 AOSP for x86_64, all necessary flags are enabled during kernel build, including `CONFIG_DEBUG_INFO_BTF`

bpftool version: `not sure, provided by xmake-repo`
libbpf: `432a4348579e0049af45c6712a2c1430f607b086`

```bash
> file /sys/kernel/btf/vmlinux
/sys/kernel/btf/vmlinux : data
```

Steps:
```bash
git clone --recurse-submodules https://github.com/libbpf/libbpf-bootstrap
...
xmake f -p android -a x86_64 -c --require-bpftool=y
xmake -y
```
all compiles successfully.

`minimal` works on the devices.
`bootstrap` fails:
```bash
libbpf: failed to find valid kernel BTF
libbpf: Error loading vmlinux BTF: -3
libbpf: failed to load object 'bootstrap_bpf'
libbpf: failed to load BPF skeleton 'bootstrap_bpf': -3
Failed to load and verify BPF skeleton
```

My guess is that the problem is related to maps since minimal doesn't contain any and it works.

**Comment by zebede22** [comment]
I think @waruqi  is able to help here

**Comment by waruqi** [comment]
I don't have an android environment to run and test it, you can run `xmake -rvD` to check the full compilation flags.

**Comment by zebede22** [comment]
Here is flags but not sure how it helps:
`
/home/ubuntu/.xmake/packages/n/ndk/22.0/47b07ed4d30e4abab121bb6742b9f914/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -o build/android/x86_64/release/kronos build/.objs/kronos/android/x86_64/release/kronos.cpp.o -llog -target x86_64-none-linux-android23 -gcc-toolchain /home/ubuntu/.xmake/packages/n/ndk/22.0/47b07ed4d30e4abab121bb6742b9f914/toolchains/x86_64-4.9/prebuilt/linux-x86_64 -fPIE -pie -nostdlib++ -Lbuild/android/x86_64/release -L/home/ubuntu/.xmake/packages/e/elfutils/0.189/697f812576ba4284b9c9afbf1f8ffbcc/lib -L/home/ubuntu/.xmake/packages/z/zlib/v1.3/9259ea39da1b4d2094f44a8255c962a2/lib -L/home/ubuntu/.xmake/packages/l/libintl/0.22.3/e3ed9d23ada34eb18846f29d8fd49790/lib -L/home/ubuntu/.xmake/packages/a/argp-standalone/1.3/463ea520ca4b4a6f85edce46a4bf757c/lib -s -L/home/ubuntu/.xmake/packages/n/ndk/22.0/47b07ed4d30e4abab121bb6742b9f914/sources/cxx-stl/llvm-libc++/libs/x86_64 -lbpf -ldw -lelf -lintl -largp -lz -lc++_static -lc++abi
`

**Comment by zebede22** [comment]
> I don't have an android environment to run and test it, you can run `xmake -rvD` to check the full compilation flags.

Is there a way to specify btftool version when fetching from xmake?

**Comment by waruqi** [comment]
> > I don't have an android environment to run and test it, you can run `xmake -rvD` to check the full compilation flags.
> 
> Is there a way to specify btftool version when fetching from xmake?

you need add version to https://github.com/xmake-io/xmake-repo/blob/f97b2f979f870b51ca1ef7a306fe1458625d1448/packages/l/linux-tools/xmake.lua#L13

then add version in https://github.com/libbpf/libbpf-bootstrap/blob/6aa0c77287e2c6152f679013a2cf94a2d0314f72/examples/c/xmake.lua#L46

`add_requires("linux-tool 5.16.9", ...)`

**Comment by zebede22** [comment]
> > > I don't have an android environment to run and test it, you can run `xmake -rvD` to check the full compilation flags.
> > 
> > 
> > Is there a way to specify btftool version when fetching from xmake?
> 
> you need add version to https://github.com/xmake-io/xmake-repo/blob/f97b2f979f870b51ca1ef7a306fe1458625d1448/packages/l/linux-tools/xmake.lua#L13
> 
> then add version in
> 
> https://github.com/libbpf/libbpf-bootstrap/blob/6aa0c77287e2c6152f679013a2cf94a2d0314f72/examples/c/xmake.lua#L46
> 
> `add_requires("linux-tool 5.16.9", ...)`

Used the latest version 5.16.9 but still same error.

Not sure if latest ndk will help: https://github.com/xmake-io/xmake-repo/pull/3159

**Comment by anakryiko** [comment]
If you have `/sys/kernel/btf/vmlinux` and libbpf still complains about "failed to find valid kernel BTF", then one of two things: either your application doesn't have permissions to open that file, or it has BTF that your version of libbpf doesn't understand (e.g., it's using some new BTF features that older libbpf doesn't know how to parse). There is a slight chance that /sys/kernel/btf/vmlinux is just corrupted, you should be able to validate somewhat by dumping it using bpftool:
```
bpftool btf dump file /sys/kernel/btf/vmlinux
```

**Comment by zebede22** [comment]
I have root access via adb, so the app runs as root with +x executable permission, should be no problem.
I use whatever version is libbpf-bootstrap is using, also tried master branch, same.

I tried bptftool and is successfully dumped the vmlinux, shouldn't be problem.

**Comment by zebede22** [comment]
Is there a way to debug epbf programs?

**Comment by zebede22** [comment]
I found this in `logcat`, not sure if related:
`
myapp  : type=1400 audit(0.0:547): avc: denied { bpf } for capability=39 scontext=u:r:su:s0 tcontext=u:r:su:s0 tclass=capability2 permissive=1
`

**Comment by waruqi** [comment]
> I have root access via adb, so the app runs as root with +x executable permission, should be no problem. I use whatever version is libbpf-bootstrap is using, also tried master branch, same.
> 
> I tried bptftool and is successfully dumped the vmlinux, shouldn't be problem.

I saw your android device is x86_64. you can check https://github.com/libbpf/libbpf-bootstrap/blob/6aa0c77287e2c6152f679013a2cf94a2d0314f72/examples/c/xmake.lua#L39

xmake build bpf use `vmlinux/x86`, I don't know if they match your equipment exactly. You can try to use the bpftool provided by xmake-repo to dump a copy of vmlinux and overwrite it with the specified vmlinux/x86.

**Comment by zebede22** [comment]
> > I have root access via adb, so the app runs as root with +x executable permission, should be no problem. I use whatever version is libbpf-bootstrap is using, also tried master branch, same.
> > I tried bptftool and is successfully dumped the vmlinux, shouldn't be problem.
> 
> I saw your android device is x86_64. you can check
> 
> https://github.com/libbpf/libbpf-bootstrap/blob/6aa0c77287e2c6152f679013a2cf94a2d0314f72/examples/c/xmake.lua#L39
> 
> xmake build bpf use `vmlinux/x86`, I don't know if they match your andriod device exactly. You can try to use the bpftool provided by xmake-repo to dump a copy of vmlinux and overwrite it with the specified vmlinux/x86.
> 
> https://github.com/libbpf/libbpf-bootstrap/tree/master/vmlinux/x86

I generated one via this tool
```bash
bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
```
same error :/

**Comment by zebede22** [comment]
I tried aya-rs lsm-template to test and it runs perfectly, so environment should be okay

**Comment by anakryiko** [comment]
@zebede22 can you please provide full libbpf log, including DEBUG level messages? (run `sudo ./bootstrap -v` for that). Thanks.

**Comment by slain01** [comment]
I also encountered this problem when I updated the libbpfv1.0.0 used on my Android device to the latest version a few days ago. I found that the permission check was modified in this commit: https://github.com/libbpf/libbpf/ commit/9da0dcb62149ab0a6c5711813d77a844ec6f393b
However, the "AT_EACCESS" flag is not supported on Android devices. Relevant instructions can be found in the AOSP source code: https://android.googlesource.com/platform/bionic/+/refs/heads/android13-release/libc/bionic /faccessat.cpp#50
Therefore, if you want to use BTF on Android devices, you can try to modify the libbpf source code and change the "AT_EACCESS" flag to 0, or you can use the pre-commit version of libbpf that modified the permission check.

**Comment by anakryiko** [comment]
sadness. Is there a way to detect AT_EACCESS support to teach libbpf to not do this? If it's simple enough, I can backport it to 1.3 version as well?

**Comment by anakryiko** [comment]
@slain01, @zebede22 I posted a fix upstream (https://patchwork.kernel.org/project/netdevbpf/patch/20240126220944.2497665-1-andrii@kernel.org/), it would be nice if you can apply it locally and verify that it fixes the issue on Android (I don't have ability to test on Android). Thanks!

**Comment by slain01** [comment]
> @slain01, @zebede22 I posted a fix upstream (https://patchwork.kernel.org/project/netdevbpf/patch/20240126220944.2497665-1-andrii@kernel.org/), it would be nice if you can apply it locally and verify that it fixes the issue on Android (I don't have ability to test on Android). Thanks!

Thank you for the fix! I've applied it locally and confirmed that it resolves the issue on Android. 
Before the fix: 
![image](https://github.com/libbpf/libbpf-bootstrap/assets/43878954/e12ed10b-149e-4f2e-837f-654e3c9afb1a)
After the fix, it works correctly: 
![image](https://github.com/libbpf/libbpf-bootstrap/assets/43878954/5cabf4c7-b94c-4715-b406-ab8ee90cf141)

**Comment by anakryiko** [comment]
> Thank you for the fix! I've applied it locally and confirmed that it resolves the issue on Android.

Great, thanks for confirming. The fix got applied upstream, I'm going to sync it to Github and then update submodule reference in libbpf-bootstrap to avoid this for Android users.
