### ISSUE TITLE
when compile the Rust example in libbpf-bootstrap for target  arm64 ，why build.rs use vmlinux.h is x86 ?

### ISSUE THREAD

**Issue by lichm1007** [libbpf/libbpf-bootstrap#257]
eg: xdp -> build.rs  
when use command  :   RUSTFLAGS="-C linker=/usr/bin/aarch64-linux-gnu-gcc" cargo build --target aarch64-unknown-linux-gnu   
the build.rs -> ARCH is x86_64 
 
**fn main() {
    let mut out =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set in build script"));
    out.push("xdppass.skel.rs");

    ### **println!("arch={}", ARCH);   // is  x86_64   ?**  

    SkeletonBuilder::new()
        .source(SRC)
        .clang_args(format!(
            "-I{}",
            Path::new("../../../vmlinux")
                .join(match ARCH {
                    "aarch64" => "arm64",
                    "loongarch64" => "loongarch",
                    "powerpc64" => "powerpc",
                    "riscv64" => "riscv",
                    "x86_64" => "x86",
                    _ => ARCH,
                })
                .display()
        ))
        .build_and_generate(out)
        .unwrap();
    println!("cargo:rerun-if-changed={}", SRC);
}**

**Comment by danielocfb** [comment]
It's conceivable that `ARCH` does not honor the cross compilation target. In that case we may actually have to use the `CARGO_CFG_TARGET_ARCH` environment variable. Could you try that out, by any chance?

**Comment by lichm1007** [comment]
use command :  CARGO_CFG_TARGET_ARCH=aarch64 RUSTFLAGS="-C linker=/usr/bin/aarch64-linux-gnu-gcc" cargo build --target aarch64-unknown-linux-gnu   ，  build.rs  arch is x86_64   ， can not set to aarch64

**Comment by danielocfb** [comment]
What I meant is:
```patch
--- examples/rust/xdp/build.rs
+++ examples/rust/xdp/build.rs
@@ -1,5 +1,4 @@
 use std::env;
-use std::env::consts::ARCH;
 use std::path::Path;
 use std::path::PathBuf;

@@ -12,18 +11,21 @@ fn main() {
         PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set in build script"));
     out.push("xdppass.skel.rs");

+    let arch = env::var("CARGO_CFG_TARGET_ARCH")
+        .expect("CARGO_CFG_TARGET_ARCH must be set in build script");
+
     SkeletonBuilder::new()
         .source(SRC)
         .clang_args(format!(
             "-I{}",
             Path::new("../../../vmlinux")
-                .join(match ARCH {
+                .join(match arch.as_ref() {
                     "aarch64" => "arm64",
                     "loongarch64" => "loongarch",
                     "powerpc64" => "powerpc",
                     "riscv64" => "riscv",
                     "x86_64" => "x86",
-                    _ => ARCH,
+                    _ => &arch,
                 })
                 .display()
         ))
```

**Comment by lichm1007** [comment]
thread 'main' panicked at tracecon/build.rs:32:10:
  bpf compilation failed: Build("Failed to compile obj=/tmp/.tmpE79yFE/tracecon.o with status=exit status: 1\n stdout=\n \n stderr=\n src/bpf/tracecon.bpf.c:78:5: error: no member named 'di' in 'struct pt_regs'\n   78 | int BPF_KPROBE(getaddrinfo_enter, const char *hostname, const char *service,\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n   79 |                const struct addrinfo *hints, struct addrinfo **res)\n      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:469:20: note: expanded from macro 'BPF_KPROBE'\n  469 |         return ____##name(___bpf_kprobe_args(args));                        \\\n      |                           ^~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:449:41: note: expanded from macro '___bpf_kprobe_args'\n  449 | #define ___bpf_kprobe_args(args...)     ___bpf_apply(___bpf_kprobe_args, ___bpf_narg(args))(args)\n      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_helpers.h:184:29: note: expanded from macro '___bpf_apply'\n  184 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)\n      |                             ^\nnote: (skipping 5 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:444:72: note: expanded from macro '___bpf_kprobe_args1'\n  444 | #define ___bpf_kprobe_args1(x)          ___bpf_kprobe_args0(), (void *)PT_REGS_PARM1(ctx)\n      |                                                                        ^~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:272:46: note: expanded from macro 'PT_REGS_PARM1'\n  272 | #define PT_REGS_PARM1(x) (__PT_REGS_CAST(x)->__PT_PARM1_REG)\n      |                           ~~~~~~~~~~~~~~~~~  ^\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:77:24: note: expanded from macro '__PT_PARM1_REG'\n   77 | #define __PT_PARM1_REG di\n      |                        ^\nsrc/bpf/tracecon.bpf.c:78:5: error: no member named 'si' in 'struct pt_regs'\n   78 | int BPF_KPROBE(getaddrinfo_enter, const char *hostname, const char *service,\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n   79 |                const struct addrinfo *hints, struct addrinfo **res)\n      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:469:20: note: expanded from macro 'BPF_KPROBE'\n  469 |         return ____##name(___bpf_kprobe_args(args));                        \\\n      |                           ^~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:449:41: note: expanded from macro '___bpf_kprobe_args'\n  449 | #define ___bpf_kprobe_args(args...)     ___bpf_apply(___bpf_kprobe_args, ___bpf_narg(args))(args)\n      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_helpers.h:184:29: note: expanded from macro '___bpf_apply'\n  184 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)\n      |                             ^\nnote: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:445:76: note: expanded from macro '___bpf_kprobe_args2'\n  445 | #define ___bpf_kprobe_args2(x, args...) ___bpf_kprobe_args1(args), (void *)PT_REGS_PARM2(ctx)\n      |                                                                            ^~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:273:46: note: expanded from macro 'PT_REGS_PARM2'\n  273 | #define PT_REGS_PARM2(x) (__PT_REGS_CAST(x)->__PT_PARM2_REG)\n      |                           ~~~~~~~~~~~~~~~~~  ^\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:78:24: note: expanded from macro '__PT_PARM2_REG'\n   78 | #define __PT_PARM2_REG si\n      |                        ^\nsrc/bpf/tracecon.bpf.c:78:5: error: no member named 'dx' in 'struct pt_regs'\n   78 | int BPF_KPROBE(getaddrinfo_enter, const char *hostname, const char *service,\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n   79 |                const struct addrinfo *hints, struct addrinfo **res)\n      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:469:20: note: expanded from macro 'BPF_KPROBE'\n  469 |         return ____##name(___bpf_kprobe_args(args));                        \\\n      |                           ^~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:449:41: note: expanded from macro '___bpf_kprobe_args'\n  449 | #define ___bpf_kprobe_args(args...)     ___bpf_apply(___bpf_kprobe_args, ___bpf_narg(args))(args)\n      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_helpers.h:184:29: note: expanded from macro '___bpf_apply'\n  184 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)\n      |                             ^\nnote: (skipping 3 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:446:76: note: expanded from macro '___bpf_kprobe_args3'\n  446 | #define ___bpf_kprobe_args3(x, args...) ___bpf_kprobe_args2(args), (void *)PT_REGS_PARM3(ctx)\n      |                                                                            ^~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:274:46: note: expanded from macro 'PT_REGS_PARM3'\n  274 | #define PT_REGS_PARM3(x) (__PT_REGS_CAST(x)->__PT_PARM3_REG)\n      |                           ~~~~~~~~~~~~~~~~~  ^\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:79:24: note: expanded from macro '__PT_PARM3_REG'\n   79 | #define __PT_PARM3_REG dx\n      |                        ^\nsrc/bpf/tracecon.bpf.c:78:5: error: no member named 'cx' in 'struct pt_regs'\n   78 | int BPF_KPROBE(getaddrinfo_enter, const char *hostname, const char *service,\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n   79 |                const struct addrinfo *hints, struct addrinfo **res)\n      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:469:20: note: expanded from macro 'BPF_KPROBE'\n  469 |         return ____##name(___bpf_kprobe_args(args));                        \\\n      |                           ^~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:449:41: note: expanded from macro '___bpf_kprobe_args'\n  449 | #define ___bpf_kprobe_args(args...)     ___bpf_apply(___bpf_kprobe_args, ___bpf_narg(args))(args)\n      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_helpers.h:184:29: note: expanded from macro '___bpf_apply'\n  184 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)\n      |                             ^\nnote: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:447:76: note: expanded from macro '___bpf_kprobe_args4'\n  447 | #define ___bpf_kprobe_args4(x, args...) ___bpf_kprobe_args3(args), (void *)PT_REGS_PARM4(ctx)\n      |                                                                            ^~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:275:46: note: expanded from macro 'PT_REGS_PARM4'\n  275 | #define PT_REGS_PARM4(x) (__PT_REGS_CAST(x)->__PT_PARM4_REG)\n      |                           ~~~~~~~~~~~~~~~~~  ^\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:80:24: note: expanded from macro '__PT_PARM4_REG'\n   80 | #define __PT_PARM4_REG cx\n      |                        ^\nsrc/bpf/tracecon.bpf.c:93:5: error: no member named 'ax' in 'struct pt_regs'\n   93 | int BPF_KRETPROBE(getaddrinfo_exit, int ret)\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:493:20: note: expanded from macro 'BPF_KRETPROBE'\n  493 |         return ____##name(___bpf_kretprobe_args(args));                     \\\n      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:477:40: note: expanded from macro '___bpf_kretprobe_args'\n  477 | #define ___bpf_kretprobe_args(args...) ___bpf_apply(___bpf_kretprobe_args, ___bpf_narg(args))(args)\n      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_helpers.h:184:29: note: expanded from macro '___bpf_apply'\n  184 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)\n      |                             ^\nnote: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:476:74: note: expanded from macro '___bpf_kretprobe_args1'\n  476 | #define ___bpf_kretprobe_args1(x)      ___bpf_kretprobe_args0(), (void *)PT_REGS_RC(ctx)\n      |                                                                          ^~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:279:43: note: expanded from macro 'PT_REGS_RC'\n  279 | #define PT_REGS_RC(x) (__PT_REGS_CAST(x)->__PT_RC_REG)\n      |                        ~~~~~~~~~~~~~~~~~  ^\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:84:21: note: expanded from macro '__PT_RC_REG'\n   84 | #define __PT_RC_REG ax\n      |                     ^\nsrc/bpf/tracecon.bpf.c:119:5: error: no member named 'di' in 'struct pt_regs'\n  119 | int BPF_KPROBE(tcp_v4_connect_enter, struct sock *sk, struct sockaddr *uaddr, int addr_len)\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:469:20: note: expanded from macro 'BPF_KPROBE'\n  469 |         return ____##name(___bpf_kprobe_args(args));                        \\\n      |                           ^~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:449:41: note: expanded from macro '___bpf_kprobe_args'\n  449 | #define ___bpf_kprobe_args(args...)     ___bpf_apply(___bpf_kprobe_args, ___bpf_narg(args))(args)\n      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_helpers.h:184:29: note: expanded from macro '___bpf_apply'\n  184 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)\n      |                             ^\nnote: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:444:72: note: expanded from macro '___bpf_kprobe_args1'\n  444 | #define ___bpf_kprobe_args1(x)          ___bpf_kprobe_args0(), (void *)PT_REGS_PARM1(ctx)\n      |                                                                        ^~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:272:46: note: expanded from macro 'PT_REGS_PARM1'\n  272 | #define PT_REGS_PARM1(x) (__PT_REGS_CAST(x)->__PT_PARM1_REG)\n      |                           ~~~~~~~~~~~~~~~~~  ^\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:77:24: note: expanded from macro '__PT_PARM1_REG'\n   77 | #define __PT_PARM1_REG di\n      |                        ^\nsrc/bpf/tracecon.bpf.c:119:5: error: no member named 'si' in 'struct pt_regs'\n  119 | int BPF_KPROBE(tcp_v4_connect_enter, struct sock *sk, struct sockaddr *uaddr, int addr_len)\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:469:20: note: expanded from macro 'BPF_KPROBE'\n  469 |         return ____##name(___bpf_kprobe_args(args));                        \\\n      |                           ^~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:449:41: note: expanded from macro '___bpf_kprobe_args'\n  449 | #define ___bpf_kprobe_args(args...)     ___bpf_apply(___bpf_kprobe_args, ___bpf_narg(args))(args)\n      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_helpers.h:184:29: note: expanded from macro '___bpf_apply'\n  184 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)\n      |                             ^\nnote: (skipping 3 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:445:76: note: expanded from macro '___bpf_kprobe_args2'\n  445 | #define ___bpf_kprobe_args2(x, args...) ___bpf_kprobe_args1(args), (void *)PT_REGS_PARM2(ctx)\n      |                                                                            ^~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:273:46: note: expanded from macro 'PT_REGS_PARM2'\n  273 | #define PT_REGS_PARM2(x) (__PT_REGS_CAST(x)->__PT_PARM2_REG)\n      |                           ~~~~~~~~~~~~~~~~~  ^\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:78:24: note: expanded from macro '__PT_PARM2_REG'\n   78 | #define __PT_PARM2_REG si\n      |                        ^\nsrc/bpf/tracecon.bpf.c:119:5: error: no member named 'dx' in 'struct pt_regs'\n  119 | int BPF_KPROBE(tcp_v4_connect_enter, struct sock *sk, struct sockaddr *uaddr, int addr_len)\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:469:20: note: expanded from macro 'BPF_KPROBE'\n  469 |         return ____##name(___bpf_kprobe_args(args));                        \\\n      |                           ^~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:449:41: note: expanded from macro '___bpf_kprobe_args'\n  449 | #define ___bpf_kprobe_args(args...)     ___bpf_apply(___bpf_kprobe_args, ___bpf_narg(args))(args)\n      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_helpers.h:184:29: note: expanded from macro '___bpf_apply'\n  184 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)\n      |                             ^\nnote: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:446:76: note: expanded from macro '___bpf_kprobe_args3'\n  446 | #define ___bpf_kprobe_args3(x, args...) ___bpf_kprobe_args2(args), (void *)PT_REGS_PARM3(ctx)\n      |                                                                            ^~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:274:46: note: expanded from macro 'PT_REGS_PARM3'\n  274 | #define PT_REGS_PARM3(x) (__PT_REGS_CAST(x)->__PT_PARM3_REG)\n      |                           ~~~~~~~~~~~~~~~~~  ^\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:79:24: note: expanded from macro '__PT_PARM3_REG'\n   79 | #define __PT_PARM3_REG dx\n      |                        ^\nsrc/bpf/tracecon.bpf.c:130:5: error: no member named 'ax' in 'struct pt_regs'\n  130 | int BPF_KRETPROBE(tcp_v4_connect_exit, int ret)\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:493:20: note: expanded from macro 'BPF_KRETPROBE'\n  493 |         return ____##name(___bpf_kretprobe_args(args));                     \\\n      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:477:40: note: expanded from macro '___bpf_kretprobe_args'\n  477 | #define ___bpf_kretprobe_args(args...) ___bpf_apply(___bpf_kretprobe_args, ___bpf_narg(args))(args)\n      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_helpers.h:184:29: note: expanded from macro '___bpf_apply'\n  184 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)\n      |                             ^\nnote: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:476:74: note: expanded from macro '___bpf_kretprobe_args1'\n  476 | #define ___bpf_kretprobe_args1(x)      ___bpf_kretprobe_args0(), (void *)PT_REGS_RC(ctx)\n      |                                                                          ^~~~~~~~~~~~~~~\n/tmp/.tmpQvyguC/bpf/src/bpf/bpf_tracing.h:279:43: note: expanded from macro 'PT_REGS_RC'\n  279 | #define PT_REGS_RC(x) (__PT_REGS_CAST(x)->__PT_RC_REG)\n

**Comment by lichm1007** [comment]
now  xxx.bpf.c  code use  arm64 vmlinux.h  ,  but  why libbpf use x86  in  bpf_tracing.h ?

**Comment by danielocfb** [comment]
Can you clean up the error snippet you pasted? I can't read it.

**Comment by anakryiko** [comment]
bpf_tracing.h expects to have correct `__TARGET_ARCH_xxx` set for target host architecture (it tries to guess it if it's not specified, so of course it doesn't work for cross-compilation cases). See https://github.com/libbpf/libbpf-bootstrap/blob/master/examples/c/Makefile#L107 how we specify it for C examples.

**Comment by danielocfb** [comment]
> bpf_tracing.h expects to have correct `__TARGET_ARCH_xxx` set for target host architecture (it tries to guess it if it's not specified, so of course it doesn't work for cross-compilation cases). See https://github.com/libbpf/libbpf-bootstrap/blob/master/examples/c/Makefile#L107 how we specify it for C examples.

I think `libbpf-cargo` may be setting this define to the wrong architecture, because it also relies on the `ARCH` constant:
https://github.com/libbpf/libbpf-rs/blob/39b62951cc0f59e128c2070c278913918cc898aa/libbpf-cargo/src/build.rs#L184-L191
