### ISSUE TITLE
Android build are failing (elfutils problem again?)

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf-bootstrap#288]
Seems like Android builds started failing again. I'd appreciate someone with access to Android to take a look.

See https://github.com/libbpf/libbpf-bootstrap/actions/runs/10999328127 for failure details.

cc @waruqi

**Comment by waruqi** [comment]
I will look at it in these days.

**Comment by waruqi** [comment]
try it again. https://github.com/xmake-io/xmake-repo/pull/5335

**Comment by anakryiko** [comment]
@waruqi seems to be working fine now, thanks a lot for the fix!
