### ISSUE TITLE
Old libbpf-rs versions in Rust examples

### ISSUE THREAD

**Issue by 0xB10C** [libbpf/libbpf-bootstrap#295]
While looking for example for libbpf-rs `0.24`, I noticed the Rust examples use quite old libbpf-rs versions. The `libbpf-rs` API has changed quite a bit in recent versions. It would be good to have examples that work with libbpf-rs `0.24`.

https://github.com/libbpf/libbpf-bootstrap/blob/4a567f229efe8fc79ee1a2249569eb6b9c02ad1b/examples/rust/xdp/Cargo.toml#L13

https://github.com/libbpf/libbpf-bootstrap/blob/4a567f229efe8fc79ee1a2249569eb6b9c02ad1b/examples/rust/tracecon/Cargo.toml#L10

https://github.com/libbpf/libbpf-bootstrap/blob/4a567f229efe8fc79ee1a2249569eb6b9c02ad1b/examples/rust/profile/Cargo.toml#L11

**Comment by 0xB10C** [comment]
Note that there are up-to-date examples in https://github.com/libbpf/libbpf-rs/tree/master/examples if anyone else is looking for them.

**Comment by danielocfb** [comment]
Yeah, we should update. I was going to set up Dependabot, but it's probably too much noise for the maintainers...
