### ISSUE TITLE
uprobe example

### ISSUE THREAD

**Issue by iagainst138** [libbpf/libbpf-bootstrap#3]
Would it be possible to add an example of how work with uprobes?

**Comment by anakryiko** [comment]
That's a good idea, I'll try to add uprobe example, as it has few extra bits to make it work.

Meanwhile, if you are blocked and would like some inspiration, feel free to check out this BPF selftest:

https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/progs/test_attach_probe.c
https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/prog_tests/attach_probe.c

**Comment by iagainst138** [comment]
Thanks.

**Comment by anakryiko** [comment]
@iagainst138 https://github.com/libbpf/libbpf-bootstrap/pull/6 adds uprobe/uretprobe minimal example.

**Comment by iagainst138** [comment]
Thanks that works perfectly and clears up the questions I had.
