### ISSUE TITLE
vmlinux.h question

### ISSUE THREAD

**Issue by ipolevoy-work** [libbpf/libbpf-bootstrap#31]
In the vmlinux.h on line 950 appears:
`struct hlist_node pid_links[4];`
shouldn't it be 
`struct pid_link pid_links[4];`
instead?

**Comment by chenhengqi** [comment]
https://elixir.bootlin.com/linux/v5.8.18/source/include/linux/sched.h#L842

**Comment by ipolevoy-work** [comment]
Thanks @chenhengqi  that was really helpful
Does it mean that libbpf doesn't support kernels < 5.8.18 or this is a generic representation for all the bpf supported kernels?

**Comment by anakryiko** [comment]
Libbpf supports any kernel version. vmlinux.h doesn't have to match exact kernel version as long as all the types and their fields are what you expect. If there was some change in most recent kernel that you need (like hlist_node to pid_link change), then you'll need to re-generate vmlinux.h, or you can just define your own definition of a data structure you'd like to read with BPF CO-RE. vmlinux.h is just a convenient way to have most of kernel types defined for you, so  that you don't have to re-define them manually.
