### ISSUE TITLE
Optimize profile demo for virtual machine compatibility

### ISSUE THREAD

**Issue by flearc** [libbpf/libbpf-bootstrap#313]
When running the `profile` demo on a virtual machine, I encountered the following error:
```
# C
sudo ./profile 
Fail to set up performance monitor on a CPU/Core

# Rust
sudo ./target/release/profile
Error: Error: failed to open perf event

Caused by:
    No such file or directory (os error 2)
```
Thanks to https://github.com/libbpf/libbpf-bootstrap/issues/210#issuecomment-1698392516, it seems that in the virtual machine the `profile` demo needs different attributes to work as expected. 

Patches on virtual machines can be:

For C:
```diff
diff --git a/examples/c/profile.c b/examples/c/profile.c
index 1eab837..23c1e1e 100644
--- a/examples/c/profile.c
+++ b/examples/c/profile.c
@@ -206,9 +206,9 @@ int main(int argc, char *const argv[])
        links = calloc(num_cpus, sizeof(struct bpf_link *));

        memset(&attr, 0, sizeof(attr));
-       attr.type = PERF_TYPE_HARDWARE;
+       attr.type = PERF_TYPE_SOFTWARE;
        attr.size = sizeof(attr);
-       attr.config = PERF_COUNT_HW_CPU_CYCLES;
+       attr.config = PERF_COUNT_SW_CPU_CLOCK;
        attr.sample_freq = freq;
        attr.freq = 1;
```

For Rust:
```diff
diff --git a/examples/rust/profile/src/main.rs b/examples/rust/profile/src/main.rs
index de03e41..dd65017 100644
--- a/examples/rust/profile/src/main.rs
+++ b/examples/rust/profile/src/main.rs
@@ -52,9 +52,9 @@ fn init_perf_monitor(freq: u64) -> Result<Vec<i32>, libbpf_rs::Error> {
             buf.leak().as_mut_ptr() as *mut syscall::perf_event_attr
         )
     };
-    attr._type = syscall::PERF_TYPE_HARDWARE;
+    attr._type = syscall::PERF_TYPE_SOFTWARE;
     attr.size = mem::size_of::<syscall::perf_event_attr>() as u32;
-    attr.config = syscall::PERF_COUNT_HW_CPU_CYCLES;
+    attr.config = syscall::PERF_COUNT_SW_CPU_CLOCK;
     attr.sample.sample_freq = freq;
     attr.flags = 1 << 10; // freq = 1
     (0..nprocs)
```
```diff
diff --git a/examples/rust/profile/src/syscall.rs b/examples/rust/profile/src/syscall.rs
index eb73f3b..e697ded 100644
--- a/examples/rust/profile/src/syscall.rs
+++ b/examples/rust/profile/src/syscall.rs
@@ -54,7 +54,9 @@ pub struct perf_event_attr {
 }

 pub const PERF_TYPE_HARDWARE: u32 = 0;
+pub const PERF_TYPE_SOFTWARE: u32 = 1;
 pub const PERF_COUNT_HW_CPU_CYCLES: u64 = 0;
+pub const PERF_COUNT_SW_CPU_CLOCK: u64 = 0;

 extern "C" {
     fn syscall(number: libc::c_long, ...) -> libc::c_long;
```

It will be nice the `profile` demo works on both physical machines and virtual machines.

- use correct attributes based on detect whether the profile demo is running on a virtual machine or a physical machine at runtime

OR
- add a note in the profile demo’s section of the README

**Comment by danielocfb** [comment]
I don't know if there are downsides to using software clock cycles, to be honest. Perhaps a tiny performance hit because the kernel executes some instruction on every context switch? Would be good to understand that.

Short of switching to software clock cycles completely, we could probably just introduce a command line switch to use one over the other.

**Comment by flearc** [comment]
> I don't know if there are downsides to using software clock cycles, to be honest. Perhaps a tiny performance hit because the kernel executes some instruction on every context switch? Would be good to understand that.
> 
> Short of switching to software clock cycles completely, we could probably just introduce a command line switch to use one over the other and perhaps hint at that when we see this "No such file or directory (os error 2)" error. I think that should be reasonably uncontroversial. Feel free to open a pull request.

Thanks for advice! A command line switch looks like a better way to handle this, I will have a try.
