### ISSUE TITLE
Question regarding the Rust Examples' Readme

### ISSUE THREAD

**Issue by tallossos** [libbpf/libbpf-bootstrap#32]
Hello!
I was wondering why you build & generate the skel manually (using `cargo libbpf <...>`) rather than using `cargo build` like you did at the end.
These commands generate another `.skel.rs` and `.mod` files plus keeping the `.bpf.o` file which `cargo build` discards automatically.
```shell
$ cd examples/rust
$ cargo libbpf build
$ cargo libbpf gen
$ cargo build --release
$ sudo ./target/release/xdp 1
<...>
```
Thanks!

**Comment by chenhengqi** [comment]
#29 introduced build script, the following commands are not required now:
```shell
$ cargo libbpf build
$ cargo libbpf gen
```

**Comment by tallossos** [comment]
Thanks for clarifying,
I've opened a [PR](https://github.com/libbpf/libbpf-bootstrap/pull/33) for removing these commands.

**Comment by tallossos** [comment]
The PR has been merged, closing the issue :)
