### ISSUE TITLE
what is the  function int BPF_PROG(do_unlinkat, int dfd, struct filename *name) arguments means ?

### ISSUE THREAD

**Issue by willinin** [libbpf/libbpf-bootstrap#37]
in function:  int BPF_PROG(do_unlinkat, int dfd, struct filename *name)
I don't know why the function's first argument is "do_unlinkat",  I find nothing from all included header files. And i change the "do_unlinkat"  to  random string, such as "xxxyyyy".  And everything is ok. so what is the first argument means?

**Comment by chenhengqi** [comment]
`do_unlinkat` becomes function name after macro expansion.

https://github.com/libbpf/libbpf/blob/v0.4.0/src/bpf_tracing.h#L367-L389

**Comment by willinin** [comment]
Thanks.
