### ISSUE TITLE
Process the bpftool file of x86-64 on the ARM architecture when compiling the BPF program

### ISSUE THREAD

**Issue by vicky3932** [libbpf/libbpf-bootstrap#38]
Hello:
My system uses the ARM architecture, but the bpftool file is x86-64. As a result, the following error message is displayed when the BPF program is compiled:
/bin/sh: /root/tools/libbpf-bootstrap/tools/bpftool: cannot execute binary file: Exec format error
What am I supposed to do with it?

**Comment by anakryiko** [comment]
Ideally you install the package with bpftool for your distro and architecture. If not, you can always build from source. There were discussions of providing pre-built bpftool as part of libbpf-tools (https://github.com/iovisor/bcc/tree/master/libbpf-tools) and libbpf-bootstrap, but that didn't get implemented yet. Unfortunately I myself don't have access to any other architecture besides x86-64, so it's hard for me to provide these binaries. Sorry about that!

**Comment by jameshilliard** [comment]
> If not, you can always build from source.

Is there an out of tree version of the source code for bpftool like the [libbpf](https://github.com/libbpf/libbpf) source?

**Comment by anakryiko** [comment]
> > If not, you can always build from source.
> 
> Is there an out of tree version of the source code for bpftool like the [libbpf](https://github.com/libbpf/libbpf) source?

not yet, unfortunately, but @qmonnet is looking at making one
