### ISSUE TITLE
Add install dependencies section to README

### ISSUE THREAD

**Issue by chrispsommers** [libbpf/libbpf-bootstrap#40]
For Ubuntu 20.04 I had to install libelf-dev and clang to build examples.
For Ubuntu 16.04 I had to install libz in addition to above.

**Comment by anakryiko** [comment]
Feel free to submit PR with necessary changes.

**Comment by kckeiks** [comment]
I opened a PR for this https://github.com/libbpf/libbpf-bootstrap/pull/58
