### ISSUE TITLE
bootstrap c example not working

### ISSUE THREAD

**Issue by teroz** [libbpf/libbpf-bootstrap#42]
Hi there the c bootstrap example does not run.  I'm running it on `ubuntu 20.04`

Error is

```bash
teroz@ubuntulsm:~/libbpf-bootstrap/examples/c$ sudo ./bootstrap 
[sudo] password for teroz: 
libbpf: map 'rb': failed to create: Invalid argument(-22)
libbpf: failed to load object 'bootstrap_bpf'
libbpf: failed to load BPF skeleton 'bootstrap_bpf': -22
Failed to load and verify BPF skeleton
```

**Comment by chenhengqi** [comment]
You need to upgrade your kernel to at least 5.8.

**Comment by teroz** [comment]
Oic thank you

**Comment by chairwa** [comment]
https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md

**Comment by linrl3** [comment]
> You need to upgrade your kernel to at least 5.8.

Could you explain why we need this upgrade? Thanks!
