### ISSUE TITLE
"cargo build" errors:  'bpf/bpf_helpers.h  file not found' or   'Failed to generate skeleton ... Failed to spawn rustfmt ' 

### ISSUE THREAD

**Issue by hick** [libbpf/libbpf-bootstrap#48]
when "cargo build --release",  this error (screenshot error1) came at first, I found the "bpf/bpf_helpers.h" was generated in 2 pathes ( find /home/vagrant/libbpf-bootstrap/ -name "bpf_helpers.h"  got "screenshot find"), so cop  bpf directorys one to /usr/include  (in fact I fixed "vmlinux.h not found" error in the same way after being generated by bpftool ), but got another error: screenshot error2, I got no way to continue...  BTW.  it works well for the C version in /home/vagrant/libbpf-bootstrap/examples/rust/

screenshot error1

![image](https://user-images.githubusercontent.com/38886/141127853-819c283a-2d00-450a-acee-020969e8c49f.png)

text:

```
   Compiling xdp v0.1.0 (/home/vagrant/libbpf-bootstrap/examples/rust/xdp)
error: failed to run custom build command for `xdp v0.1.0 (/home/vagrant/libbpf-bootstrap/examples/rust/xdp)`

Caused by:
  process didn't exit successfully: `/home/vagrant/libbpf-bootstrap/examples/rust/target/release/build/xdp-ea3972c5b26f2632/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Build("Failed to compile obj=/tmp/.tmpIAhV9L/xdppass.o with status=exit code: 1\n stdout=\n \n stderr=\n ./src/bpf/xdppass.bpf.c:2:10: fatal error: \'bpf/bpf_helpers.h\' file not found\n#include <bpf/bpf_helpers.h>\n
         ^~~~~~~~~~~~~~~~~~~\n1 error generated.\n\n")', xdp/build.rs:19:47
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

screenshot find

![image](https://user-images.githubusercontent.com/38886/141129355-77a6df7d-9cea-4e60-ab82-8ac9ab371813.png)

screenshot error2

![image](https://user-images.githubusercontent.com/38886/141129633-4339b302-170c-4d51-9435-d0953dd5ca53.png)

text

```
~/libbpf-bootstrap/examples/rust$ sudo cargo build --release
   Compiling tracecon v0.1.0 (/home/vagrant/libbpf-bootstrap/examples/rust/tracecon)
   Compiling xdp v0.1.0 (/home/vagrant/libbpf-bootstrap/examples/rust/xdp)
error: failed to run custom build command for `xdp v0.1.0 (/home/vagrant/libbpf-bootstrap/examples/rust/xdp)`

Caused by:
  process didn't exit successfully: `/home/vagrant/libbpf-bootstrap/examples/rust/target/release/build/xdp-ea3972c5b26f2632/build-script-build` (exit code: 101)
  --- stderr
  libbpf: elf: skipping unrecognized data section(4) .rodata.str1.1
  libbpf: elf: skipping unrecognized data section(4) .rodata.str1.1
  Warning: unrecognized map: license
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Generate("Failed to generate skeleton for /tmp/.tmpPpu8kb/xdppass.o: Failed to spawn rustfmt")', xdp/build.rs:19:47
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by anakryiko** [comment]
@hick https://github.com/libbpf/libbpf-bootstrap/pull/49 should fix all the issues. I've released latest libbpf-rs (you'd get compilation errors if you were to update to 0.13.0 version), but the immediate problem you ran into was missing vmlinux.h symlink, which was missing because someone accidentally added vmlinux into .gitignore.

Please let me know if that fixed your issue.
