### ISSUE TITLE
CPU arch for tools/bpftool

### ISSUE THREAD

**Issue by JackyYin** [libbpf/libbpf-bootstrap#53]
Currently the executable `tools/bpftool` is a `x86_64` ELF.

How am I suppose to compile the `examples/c` on an `aarch64` computer?

Could somebody help me please? Thanks.

**Comment by anakryiko** [comment]
You can override which bpftool binary to use with BPFTOOL:

```
make BPFTOO=/path/to/bpftool
```

**Comment by JackyYin** [comment]
Yes, seems like I'll have to install `libbpf` to get the binary `bpftool`, then compile with:
```
BPFTOO=$(which bpftool) make
```
