### ISSUE TITLE
git clone does not include libbpf

### ISSUE THREAD

**Issue by nanofaroque** [libbpf/libbpf-bootstrap#59]
I was running `git clone https://github.com/libbpf/libbpf-bootstrap.git` but it looks like it missed `libbpf` for obvious reason. I guess documentation should mention that. That would be helpful.

**Comment by anakryiko** [comment]
yes, because libbpf is coming through git submodule. You need to run `git submodule update --init --recursive`, which you can see in https://github.com/libbpf/libbpf-bootstrap#c-examples

**Comment by nanofaroque** [comment]
Thanks
