### ISSUE TITLE
How to generate `bpftool`?

### ISSUE THREAD

**Issue by nurdann** [libbpf/libbpf-bootstrap#65]
I would like to know how `bpftool` and `vmlinux.h` is generated on this repository to it make cross compatible between different kernel versions that have `/sys/kernel/btf/vmlinux` exposed.

I can generate `vmlinux.h` for kernel 5.15 as follows,
```
$ uname -r
5.15.0-22-generic
$ git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git -b v5.15 linux_v5.15
$ cd linux_v5.15/tools/bpf/bpftool/
$ make
$ ./bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
```
Then I can use `vmlinux.h` to compile libbpf programs.

However, if I download kernel source with tag `v5.8` I am not able to generate `vmlinux.h` on the same machine,
```
$ git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git -b v5.8 linux_v5.8
$ cd cd linux_v5.8/tools/bpf/bpftool
$ make
$ ./bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
Error: failed to load BTF from /sys/kernel/btf/vmlinux: Invalid argument
```

Does it mean that `bpftool` must be of the same version (at least major and minor version matching) when generating `vmlinux.h`? So, this would explain why `bpftool` and `vmlinux.h` are included in the version control because, for example, if these files are generated on the fly in a container with mismatched host kernel and bpftool versions, the build can fail?

If yes, how do you go about picking which kernel version to use to compile libbpf program?

**Comment by anakryiko** [comment]
No, not really. You generally need "recent enough" bpftool, but it will handle older kernels just fine. I suspect in this case bpftool built from 5.8 kernel sources just doesn't handle BTF_KIND_FLOAT type that was introduced after 5.8. If you build bpftool from 5.15 and run it against 5.8 kernel it should work fine.

But generally, bpftool version is independent. We now also have Github mirror for bpftool, so you can build it from there: https://github.com/libbpf/bpftool/

I want to stop including prebuilt version of bpftool (to allow non-x86-64 builds of libbpf-bootstrap) and instead build it from sources (using the above Github repo). Just like we are going to do it for libbpf-tools. See https://github.com/iovisor/bcc/pull/3889/commits/03163a6c0f42ec70e047b318e9987b68e36ee28d for reference. If you'd like to contribute, wiring up bpftool from Github repo would be a great help!

As for vmlinux.h, you generally don't have to re-generate it very often or from very recent kernel. It just depends on types you are expecting to program against. If some latest kernel has some field that you'd like to reference, it would be more convenient to generate vmlinux.h from most recent kernel. But often old kernel's vmlinux.h is totally fine even for much more recent kernels. Please refer to https://nakryiko.com/posts/bpf-core-reference-guide/#defining-own-co-re-relocatable-type-definitions (and one section after the above one) for some more understanding of the role of vmlinux.h and how you can "complement" it with your own type definitions.

**Comment by nurdann** [comment]
I am very much open to contribute. From what I understand by making https://github.com/libbpf/bpftool/ a submodule, when `bpftool` is being built it will use libraries that are specific to an architecture so you wouldn't have to include multiple binaries in the version control? So, the steps are to exactly replicate how https://github.com/iovisor/bcc/commit/03163a6c0f42ec70e047b318e9987b68e36ee28d is being built.
Thanks for response!

**Comment by anakryiko** [comment]
yes, exactly
