### ISSUE TITLE
XDP rust example

### ISSUE THREAD

**Issue by marcsfran** [libbpf/libbpf-bootstrap#67]
I compiled the program but when I try to attach it to an interface with `sudo ./target/release/xdp 1` I get this message 
_libbpf: elf: skipping unrecognized data section(4) .rodata.str1.1
..........._ 
I know this is a warning message but how to fix it?

**Comment by marcsfran** [comment]
Answer [here](https://github.com/libbpf/libbpf-bootstrap/issues/12#issuecomment-785303374)

**Comment by anakryiko** [comment]
It's been implemented since, maybe we need to update libbpf version or something.
