### ISSUE TITLE
Building using cmake is not working

### ISSUE THREAD

**Issue by mariuszbarczak** [libbpf/libbpf-bootstrap#70]
When trying to build the project using cmake, I've got the following error:

bash: line 1: /home/mariusz/git/libbpf-bootstrap/examples/c/../../tools/bpftool: No such file or directory
make[2]: *** [CMakeFiles/bootstrap.dir/build.make:74: bootstrap.skel.h] Error 127
make[2]: *** Deleting file 'bootstrap.skel.h'
make[1]: *** [CMakeFiles/Makefile2:145: CMakeFiles/bootstrap.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by mariuszbarczak** [comment]
I added ExternalProject_Add in examples/c/CMakeLists.txt for bpftool, it started working. Is it acceptable?

**Comment by anakryiko** [comment]
@danobi can you please take a look if you get a chance? But either way, @JackyYin, please go ahead and submit your fix, thank you!

**Comment by danobi** [comment]
The submitted fix lgtm

**Comment by anakryiko** [comment]
Closed by https://github.com/libbpf/libbpf-bootstrap/pull/73

**Comment by mariuszbarczak** [comment]
Thanks Guys for fixing this.
