### ISSUE TITLE
Unable to build minimal example with Makefile

### ISSUE THREAD

**Issue by mik90** [libbpf/libbpf-bootstrap#72]
I pulled down the repo and  init'd the submodules
```bash
mike@framework:~/Development/libbpf-bootstrap$ git submodule init
mike@framework:~/Development/libbpf-bootstrap$ git submodule update
Cloning into '/home/mike/Development/libbpf-bootstrap/bpftool'...
Cloning into '/home/mike/Development/libbpf-bootstrap/libbpf'...
Submodule path 'bpftool': checked out 'cdd0b425fce958e3d02424c9d0296e6d0f7e323f'
Submodule path 'libbpf': checked out '9c44c8a8e01cf86bc801c3b72324358d5ea99e50'

mike@framework:~/Development/libbpf-bootstrap$ cd examples/c/
mike@framework:~/Development/libbpf-bootstrap/examples/c$ make minimal
  MKDIR    .output
  MKDIR    .output/libbpf

... (omitting a bunch of build output)

 INSTALL  /home/mike/Development/libbpf-bootstrap/examples/c/.output//libbpf/libbpf.a 
  BPF      .output/minimal.bpf.o
  MKDIR    bpftool/
  BPFTOOL  bpftool/bpftool
...                        libbfd: [ OFF ]
...        disassembler-four-args: [ OFF ]
...                          zlib: [ on  ]
...                        libcap: [ OFF ]
...               clang-bpf-co-re: [ on  ]
  MKDIR    /home/mike/Development/libbpf-bootstrap/examples/c/.output/bpftool//libbpf/
make[2]: *** /home/mike/Development/libbpf-bootstrap/bpftool/libbpf/src: No such file or directory.  Stop.
make[1]: *** [Makefile:44: /home/mike/Development/libbpf-bootstrap/examples/c/.output/bpftool//libbpf/libbpf.a] Error 2
make: *** [Makefile:65: /home/mike/Development/libbpf-bootstrap/examples/c/.output/bpftool/bpftool] Error 2
```

bpftool takes libbpf as a submodule but never inits it so there's nothing in that dir. Is there any (easy) way to get it so that bpftool just uses the libbpf from this repo or can we just have it init its own submodule in this makefile?

**Comment by anakryiko** [comment]
Check build instructions at https://github.com/libbpf/libbpf-bootstrap#c-examples, it suggests to run `git submodule update --init --recursive` which will check out nested submodules as well.

But answering you direct question, doesn't seem like bpftool's Makefile allows to override where libbpf sources are. Not sure if we actually want to allow that, but just in case cc @qmonnet for an opinion.

**Comment by mik90** [comment]
> Check build instructions at https://github.com/libbpf/libbpf-bootstrap#c-examples, it suggests to run `git submodule update --init --recursive` which will check out nested submodules as well.


Ah! I feel like a dummy. Thanks for the pointer.

**Comment by qmonnet** [comment]
> doesn't seem like bpftool's Makefile allows to override where libbpf sources are. Not sure if we actually want to allow that

Something similar [was raised on the bpftool repo](https://github.com/libbpf/bpftool/issues/13) some time ago. I'm not against providing a way to override the path for libbpf, but I fear this might lead to confusion if users attempt to use a libbpf version which is not recent enough, or if they try to use the version installed on their system but without having the sources (given that bpftool needs some libbpf headers that are not exported as part of the regular user API).

**Comment by mik90** [comment]
Makes sense to me. I'll close this issue since it's already solved by the documentation.

Thanks for the quick responses!
