### ISSUE TITLE
bpf_printk doesn't create data on trace_pipe

### ISSUE THREAD

**Issue by andreybleme** [libbpf/libbpf-bootstrap#75]
My minimal app executes correctly:

![image](https://user-images.githubusercontent.com/5385383/169928889-a92bfc26-85e1-4ea0-a77a-379769f6eecf.png)

But when I cat the "/sys/kernel/debug/tracing/trace_pipe" file it looks empty:

![image](https://user-images.githubusercontent.com/5385383/169930401-33e04522-7c1e-44a7-a08c-d478f55b6e04.png)

I'm running a Ubuntu 22.04 LTS docker container on privileged mode.

This is how I have manually mounted my debugfs:
`mount -t debugfs none /sys/kernel/debug`

Am I missing anything? Appreciate your help.

**Comment by anakryiko** [comment]
Not really, but I've had cases when something in kernel "broke" w.r.t. trace_pipe and BPF program stopped emitting anything into it. Can you try rebooting and trying ./minimal again before you do anything else with the system?

I also see 
```
mount | rg debug
debugfs on /sys/kernel/debug type debugfs (rw,relatime,mode=755)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime)
```

So maybe try mounting tracefs as well?

**Comment by andreybleme** [comment]
Thanks for replying @anakryiko!
After mounting tracefs `mount -t tracefs nodev /sys/kernel/tracing`, I see:

```
$ mount | rg debug
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime)
```

And the BPF program still doesn't write into `/sys/kernel/debug/tracing/trace_pipe`.
Interesting that when I cat, tail, or try to open the trace_pipe file with vi, the process doesn't finish with the empty output as it does with regular empty files. It actually gets stuck:

![image](https://user-images.githubusercontent.com/5385383/169930401-33e04522-7c1e-44a7-a08c-d478f55b6e04.png)

Already tried mounting debugfs and tracefs again, restarting the container etc... Any additional ideas?

**Comment by anakryiko** [comment]
I have no idea, tbh. If you are trying it from inside the container, have you tried reading that file from outside any container? Also make sure that you don't have any other process opening this file, because I think trace_pipe doesn't support multiple readers reading it simultaneously.

**Comment by andreybleme** [comment]
I see. I'm executing this by running "./minimal", and after I see the dots from the userspace application indicating the BPF program is running, I stop the processes (CTRL + C) and then run the cat command. Should I be checking for debug messages in a different way?

**Comment by anakryiko** [comment]
you can run cat in parallel, but even if you run afterwards you should still see previous output.

Do you have a chance to try this on some other system? It might be some (unknown to me) kernel config dependencies. Other than that, I'm not sure how to help you.

**Comment by Arvintian** [comment]
This may causes by the pid namespace. I had the same problem in wsl https://github.com/microsoft/WSL/issues/8461. The same as you are run the BPF program in the container, it pid namespace not is global namespace. Tansks @X-QIANG.

**Comment by lzh-lab** [comment]
I have the same problem in a host and reboot solved it.

**Comment by novitoll** [comment]
Make sure that `tracing_on` is enabled.

```
echo 1 > /sys/kernel/debug/tracing/tracing_on
cat /sys/kernel/debug/tracing/trace_pipe
```
