### ISSUE TITLE
make: *** [.output/minimal.skel.h] Error 139

### ISSUE THREAD

**Issue by RuchiSaluja8** [libbpf/libbpf-bootstrap#89]
Hi,

When running `make minimal` from `examples/c folder`, I am getting the following error :
```  
GEN-SKEL .output/minimal.skel.h
Segmentation fault (core dumped)
Makefile:110: recipe for target '.output/minimal.skel.h' failed
make: *** [.output/minimal.skel.h] Error 139
make: *** Deleting file '.output/minimal.skel.h'

```

The steps I have followed for installation are :
```
git clone https://github.com/libbpf/libbpf-bootstrap.git
git submodule update --init --recursive
cd examples/c
make minimal

```
I have also googled for Error 139 and have also tried the solution in the closed issues #69 #70 #72  #15 but couldn't find a solution that works for me.
I and gone through the Makefile line 109 - 110. I tried removing `| $(OUTPUT) $(BPFTOOL)` from line 109 `$(OUTPUT)/%.skel.h: $(OUTPUT)/%.bpf.o | $(OUTPUT) $(BPFTOOL)` but that too didn't work. 

The current version of clang and kernel installed on Ubuntu 18.04:
![image](https://user-images.githubusercontent.com/90855508/176769070-619b830e-efad-4ab8-a40a-1b8440f5db70.png)

I am not sure what's missing.

**Comment by ThinkerYzu1** [comment]
It is necessary to generate skeletons with bpftool.  The steps you provide work for me.  Could you run bpftool manually to see what will happen? It is even better to get a stack trace with gdb.

**Comment by RuchiSaluja8** [comment]
I am not sure if this is what you meant by running bpftool manually.. I am fairly new to libbpf and bpftool. Based on my understanding till now, I tried running this bpftool command : `bpftool --debug prog load /home/imgadmin/libbpf-bootstrap/examples/c/.output/minimal.bpf.o /home/imgadmin/Desktop/libbpf-test-dir/minimal.skel.h` and got an error:

```
root@l156311423:~# bpftool --debug prog load /home/imgadmin/libbpf-bootstrap/examples/c/.output/minimal.bpf.o /home/imgadmin/Desktop/libbpf-test-dir/minimal.skel.h
libbpf: loading /home/imgadmin/libbpf-bootstrap/examples/c/.output/minimal.bpf.o
libbpf: section(1) .text, size 0, link 0, flags 6, type=1
libbpf: skip section(1) .text
libbpf: section(2) tp/syscalls/sys_enter_write, size 104, link 0, flags 6, type=1
libbpf: found program tp/syscalls/sys_enter_write
libbpf: section(3) license, size 13, link 0, flags 3, type=1
libbpf: license of /home/imgadmin/libbpf-bootstrap/examples/c/.output/minimal.bpf.o is Dual BSD/GPL
libbpf: section(4) .bss, size 4, link 0, flags 3, type=8
libbpf: section(5) .rodata, size 28, link 0, flags 2, type=1
libbpf: section(6) .symtab, size 192, link 8, flags 0, type=2
libbpf: section(7) .reltp/syscalls/sys_enter_write, size 32, link 6, flags 0, type=9
libbpf: section(8) .strtab, size 126, link 0, flags 0, type=3
libbpf: skip section(8) .strtab
libbpf: Corrupted ELF file: index of strtab invalid
Error: failed to open object file
```
Seems like there is an issue with the object file itself.

Can you tell me if I should try some other bpftrace command manually? 

Also, I could see the command of GEN_SKEL even without specifying V=1.

**Comment by chenhengqi** [comment]
Try using a newer version of LLVM.

**Comment by RuchiSaluja8** [comment]
Thanks for the suggestion @chenhengqi. I have installed the latest version of LLVM (after following the steps given [here](https://docs.cilium.io/en/v1.11/bpf/#tooling-llvm) and adding the build directory's path to environment). 
But I still see the same error when running make command.

![Screenshot from 2022-07-05 11-51-52](https://user-images.githubusercontent.com/90855508/177262807-02c68343-7baa-434a-a0e9-990f7f3a9af0.png)

PS I also have other versions of LLVM and clang installed for other software. Will removing those versions solve this issue?

**Comment by ThinkerYzu1** [comment]
> Also, I could see the command of GEN_SKEL even without specifying V=1.
If you run `make V=1 minimal`, you should see that GEN_SKEL is expanded to `XXXXX
/bpftool gen skeleton .output/minimal.bpf.o > .output/minimal.skel.h`.
The issue here is that bpftool fails to generate the skeleton. libbpf-bootstrap builds its bpftool instead of using the system one.
It may help if you generate the skeleton manually with the bpftool that is built by libbpf-bootstrap.  It would be even better to have a stactrace.

**Comment by anakryiko** [comment]
make sure you are compiling BPF source code with `-g` compiler flag, which will make Clang generate BTF information.

But crash shouldn't happen anyway, so can you share object file you are using to generate skeleton?

**Comment by RuchiSaluja8** [comment]
> Thanks for the suggestion @chenhengqi. I have installed the latest version of LLVM (after following the steps given [here](https://docs.cilium.io/en/v1.11/bpf/#tooling-llvm) and adding the build directory's path to environment). But I still see the same error when running make command.
> 
> ![Screenshot from 2022-07-05 11-51-52](https://user-images.githubusercontent.com/90855508/177262807-02c68343-7baa-434a-a0e9-990f7f3a9af0.png)
> 
> PS I also have other versions of LLVM and clang installed for other software. Will removing those versions solve this issue?

After updating LLVM and CLang, I cloned this repository again and got different errors on running `make minimal`:
[https://gist.github.com/RuchiSaluja8/739b91f05169b0bc1ff108e514da3f25](https://gist.github.com/RuchiSaluja8/739b91f05169b0bc1ff108e514da3f25) 

@ThinkerYzu1 There is no gen skeleton output for minimal this time, only for profiler. The output for `make V=1 minimal` is also in the gist link mentioned above.
@anakryiko BPF code compilation is done with `-g` flag. There was no .o file generated for minimal this time.

However, running `CLANG=Nope make -j8 minimal` worked to resolve the errors I was getting.

**Comment by anakryiko** [comment]
@RuchiSaluja8 https://github.com/libbpf/libbpf-bootstrap/pull/92 should help with bpftool building issues

as for no .o, make clean and try again (but with older Clang to reproduce it)

**Comment by anakryiko** [comment]
@RuchiSaluja8 actually, I think your original crash issue will be solved by https://github.com/libbpf/libbpf-bootstrap/pull/93, bpftool had issue with .bpf.o files that don't have BTF and it was fixed, but libbpf-bootstrap didn't have that fix in its bpftool submodule yet. I've updated bpftool to latest.
