### ISSUE TITLE
[error] compiling error with makefile

### ISSUE THREAD

**Issue by Teanix** [libbpf/libbpf-bootstrap#96]
MKDIR    .output
  MKDIR    .output/libbpf
  LIB      libbpf.a
  MKDIR    /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/bpf.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/btf.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/libbpf.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/libbpf_errno.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/netlink.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/nlattr.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/str_error.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/libbpf_probes.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/bpf_prog_linfo.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/btf_dump.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/hashmap.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/ringbuf.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/strset.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/linker.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/gen_loader.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/relo_core.o
  CC       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/staticobjs/usdt.o
  AR       /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/libbpf.a
  INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h usdt.bpf.h
  INSTALL  /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/libbpf.pc
  INSTALL  /root/proj/libbpf-bootstrap/examples/c/.output//libbpf/libbpf.a 
  BPF      .output/minimal.bpf.o
  MKDIR    bpftool
  BPFTOOL  bpftool/bootstrap/bpftool
...                        libbfd: [ OFF ]
...        disassembler-four-args: [ OFF ]
...                          zlib: [ on  ]
...                        libcap: [ on  ]
...               clang-bpf-co-re: [ OFF ]
make[1]: *** No rule to make target “/root/proj/libbpf-bootstrap/bpftool/libbpf/src/hashmap.h”，need by “/root/proj/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/libbpf/include/bpf/hashmap.h” stop.
make: *** [Makefile:89：/root/proj/libbpf-bootstrap/examples/c/.output/bpftool/bootstrap/bpftool] error 2

------

how can i fix it ?

**Comment by Teanix** [comment]
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Comment by chenhengqi** [comment]
`git submodule update --init --recursive`

**Comment by Teanix** [comment]
> 

谢谢 成功解决了
